### ISSUE TITLE
Object has no method logerror

### ISSUE THREAD

**Issue by krmmalik** [haraka/Haraka#126]
Im getting the above error message when doing `node haraka.js` .
It refers to line 38 on config.js where logger.logerror is being called from logger.js

I checked logger.js and there really doesnt seem to be a logerror method defined in there?

Any help please?

**Comment by DaAwesomeP** [comment]
**I solved it!** I was running it the script-style with `node haraka.js` as opposed to the executable-style `haraka`. I wanted to use this since I am using NVM. It also says to do this in the git install instructions. I'm not sure what causes Haraka to run differently, but that is definitely it.

I was having this problem on Debian 8. I have with NodeJS v0.10.38, NodeJS v0.12.4, and io.js v2.0.2, but I always had the same error:
```
/usr/local/node/lib/node_modules/Haraka/configfile.js:93
        logger.logerror('Error watching directory ' + cp + '(' + e + ')');
               ^
TypeError: logger.logerror is not a function
    at Object.cfreader.watch_dir (/usr/local/node/lib/node_modules/Haraka/configfile.js:93:16)
    at Object.cfreader.read_config (/usr/local/node/lib/node_modules/Haraka/configfile.js:161:18)
    at Object.config.get (/usr/local/node/lib/node_modules/Haraka/config.js:15:28)
    at Object.logger._init_loglevel (/usr/local/node/lib/node_modules/Haraka/logger.js:118:28)
    at Object.<anonymous> (/usr/local/node/lib/node_modules/Haraka/logger.js:163:8)
    at Module._compile (module.js:431:26)
    at Object.Module._extensions..js (module.js:449:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
```
There must be two problems. The first being that an error is caught and the second being that it is is failing to log that error.

**Comment by ruandao** [comment]
I get the same problem after i run it with pm2 `pm2 start $(which haraka) -- -c xxx`

This problem appear, even i reinstall Haraka

@DaAwesomeP how to solved the problem?

**Comment by Dexus** [comment]
@ruandao you need to clone haraka from git or use one of the releases (zip/tar.gz) and then go into the haraka folder and use `pm2 start ./haraka -- -c xxx`.

**Comment by ruandao** [comment]
@Dexus thank you

**Comment by Dexus** [comment]
@ruandao btw: you dont need to use `-- -c xxx` the config will used from the config dir in the haraka folder...

and you dont need pm2 also, haraka can run as deamon...
