### ISSUE TITLE
2.7.1 plugin loading broken

### ISSUE THREAD

**Issue by msimerson** [haraka/Haraka#1270]
@Synchro and I just ran into this:

````
loglevel: LOGINFO
Starting up Haraka version 2.7.1
[INFO] [-] [core] Loading plugins
[INFO] [-] [core] Loading plugin: process_title
[CRIT] [-] [core] Compiling plugin: process_title failed
[CRIT] [-] [core] Error: Cannot find module 'process_title'
[CRIT] [-] [core]     at Function.Module._resolveFilename (module.js:336:15)
[CRIT] [-] [core]     at Function.Module._load (module.js:286:25)
[CRIT] [-] [core]     at Module.require (module.js:365:17)
[CRIT] [-] [core]     at require (module.js:384:17)
[CRIT] [-] [core]     at /usr/local/lib/node_modules/Haraka/plugins.js:398:23
[CRIT] [-] [core]     at /usr/local/haraka/plugins/process_title/package.json:1:9
[CRIT] [-] [core]     at ContextifyScript.Script.runInNewContext (vm.js:18:15)
[CRIT] [-] [core]     at Object.exports.runInNewContext (vm.js:49:17)
[CRIT] [-] [core]     at Object.plugins._load_and_compile_plugin (/usr/local/lib/node_modules/Haraka/plugins.js:236:12)
[CRIT] [-] [core]     at Object.plugins.load_plugin (/usr/local/lib/node_modules/Haraka/plugins.js:172:26)
[NOTICE] [-] [core] Shutting down
````

Reverting [this commit](https://github.com/haraka/Haraka/commit/ff858b8db8b124e44db6919ae139b0fdcb3bfd48) works for both of us to get 2.7.1 working.

**Comment by msimerson** [comment]
PR #1242

**Comment by baudehlo** [comment]
Damn. That may be something that also broke what @smfreegard was talking to me about.

Let's just revert it and push 2.7.2. It has no functional improvement.

**Comment by msimerson** [comment]
Works for me.

Matt

(I was going to try figuring out what it was supposed to later tonight.)

**Comment by baudehlo** [comment]
Just waiting for Travis to finish. I'll merge and publish etc once done.

**Comment by baudehlo** [comment]
Fixed. Pushed. Published. Blog updated.

Sorry!
