### ISSUE TITLE
spf fails

### ISSUE THREAD

**Issue by vivek779** [haraka/Haraka#1413]
Hello haraka team i was working on your server was able to enable dkim and dmarc on your haraka server but not able to enable spf as i am new to this field don't knew much what to enter in that spf.ini and there is no default file available in content to see what i should enter . I entered 
v=spf1 mx a -all         
 in spf.ini file and spf plugins fails please guide log are as below

```
[CRIT] [9875E4B9-993E-4650-91CF-654F572F2275] [core] Plugin spf failed: ReferenceError: plugin is not defined
    at SPF.log_debug (/usr/local/lib/node_modules/Haraka/plugins/spf.js:8:12)
    at SPF.check_host (/usr/local/lib/node_modules/Haraka/spf.js:169:10)
    at Plugin.exports.hook_helo.exports.hook_ehlo (/usr/local/lib/node_modules/Haraka/plugins/spf.js:88:9)
    at Object.plugins.run_next_hook (/usr/local/lib/node_modules/Haraka/plugins.js:465:28)
    at Object.plugins.run_hooks (/usr/local/lib/node_modules/Haraka/plugins.js:381:13)
    at /usr/local/lib/node_modules/Haraka/connection.js:1191:17
    at Connection.reset_transaction (/usr/local/lib/node_modules/Haraka/connection.js:580:17)
    at Connection.cmd_ehlo (/usr/local/lib/node_modules/Haraka/connection.js:1188:10)
    at Connection.process_line (/usr/local/lib/node_modules/Haraka/connection.js:276:29)
    at Connection._process_data (/usr/local/lib/node_modules/Haraka/connection.js:419:18)
 ```

**Comment by Dexus** [comment]
Hi @vivek779 

first of all, SPF dont need an INI-configuration file.

You need to create a DNS recorde 

`@        TXT "v=spf1 mx a -all"`

So if I don't missunderstand you, you have also the DMARC not configured for your service via DNS.

Please use Google to find out how to configure SPF via DNS. There are some good "Generators" for it.

Regards Josef

**Comment by Dexus** [comment]
And witch version you use? Please make sure if you report a "Issue" that you post also your used version and if you make changes to our default scripts, that you have changed something.

**Comment by smfreegard** [comment]
This is definitely not using an up-to-date version of Haraka because the stack trace line numbers don't match the current plugin.  So if this was a bug once upon a time, then it's been fixed already.

**Comment by vivek779** [comment]
Next time ill keep in this in mind this version i was using  Haraka version 2.8.0-alpha.9

**Comment by vivek779** [comment]
Could you please tell me any default code so that i update my proper credentials accordingly in spf.ini
for eg if i have made dkim and dmarc for abc.com pointed at 1.2.3.4 ip then how would i entered in spf.ini

**Comment by Dexus** [comment]
BTW it's a true bug:

```js
// spf

var SPF = require('./spf').SPF;
var net_utils = require('./net_utils');

// Override logging in SPF module
SPF.prototype.log_debug = function (str) {
    return plugin.logdebug(str);
};

exports.register = function () {
    var plugin = this;
    plugin.load_config();
};
```

I think the overloading need to be done in the register function or what do you think? @smfreegard @msimerson

**Comment by smfreegard** [comment]
Ok - I checked by local copy and it's different - I must have hit this bug and not updated the main repo:

`````
// Override logging in SPF module
SPF.prototype.log_debug = function (str) {
    return plugin.logdebug(str);
};
`````

Should be:

`````
// Override logging in SPF module
SPF.prototype.log_debug = function (str) {
    return exports.logdebug(str);
};
`````

**Comment by vivek779** [comment]
Should i change my code according to dexus suggestion then spf error would be solvedd??

**Comment by Dexus** [comment]
You can change the code to that what @smfreegard have written. Thats should fix the crash.

**Comment by vivek779** [comment]
Thanks it works errors gone but it showing in tmp error in mails spf section please guide me what mistake i am doing or suggest me to where i should look i have added dkim dmarc and spf to abc.com which has already dkim dmarc and spf records for other services are they  conflicting   ?

**Comment by pstadler** [comment]
Unfortunately, the fix done with #1416 is breaking the spf plugin.

```
[CRIT] [4BC284C5-7432-4C4A-BB0D-CBA188D1C84E] [core] Plugin spf failed: TypeError: plugin.logdebug is not a function
   at SPF.log_debug (node_modules/Haraka/plugins/spf.js:9:19)
   at SPF.check_host (node_modules/Haraka/spf.js:169:10)
   at Plugin.exports.hook_helo.exports.hook_ehlo (node_modules/Haraka/plugins/spf.js:89:9)
   at Object.plugins.run_next_hook (node_modules/Haraka/plugins.js:465:28)
   at callback (node_modules/Haraka/plugins.js:421:32)
   at cb (node_modules/Haraka/plugins/helo.checks.js:426:20)
   at node_modules/Haraka/plugins/helo.checks.js:546:16
   at node_modules/Haraka/net_utils.js:319:13
   at node_modules/async/lib/async.js:726:13
   at node_modules/async/lib/async.js:52:16 
```

P.S. I'm running the latest Haraka release with Node v6

**Comment by ScOut3R** [comment]
I am getting this also running Haraka 2.8.8 on Node 4.5.

```
[core] Plugin spf failed: TypeError: plugin.logdebug is not a function
    at SPF.log_debug (/usr/local/lib/node_modules/Haraka/plugins/spf.js:9:19)
    at SPF.check_host (/usr/local/lib/node_modules/Haraka/spf.js:169:10)
    at Plugin.exports.hook_helo.exports.hook_ehlo (/usr/local/lib/node_modules/Haraka/plugins/spf.js:89:9)
    at Object.plugins.run_next_hook (/usr/local/lib/node_modules/Haraka/plugins.js:486:28)
    at callback (/usr/local/lib/node_modules/Haraka/plugins.js:442:32)
    at Plugin.exports.forward_dns (/usr/local/lib/node_modules/Haraka/plugins/helo.checks.js:385:65)
    at Object.plugins.run_next_hook (/usr/local/lib/node_modules/Haraka/plugins.js:486:28)
    at callback (/usr/local/lib/node_modules/Haraka/plugins.js:442:32)
    at Plugin.exports.rdns_match (/usr/local/lib/node_modules/Haraka/plugins/helo.checks.js:216:64)
    at Object.plugins.run_next_hook (/usr/local/lib/node_modules/Haraka/plugins.js:486:28)
```

**Comment by baudehlo** [comment]
The PR #1598 should fix this.
