### ISSUE TITLE
Cannot run_tests for tests/spf.js

### ISSUE THREAD

**Issue by baudehlo** [haraka/Haraka#1544]
### Haraka version

2.8.7

### Expected behavior

`node run_tests tests/spf.js` should work and run the tests.

### Observed behavior

```
$ node run_tests tests/spf.js 
Running tests:  [ 'tests/spf.js' ]
/Users/matt/Development/Haraka/logger.js:130
    var _loglevel = config.get('loglevel', 'value', function () {
                           ^

TypeError: config.get is not a function
    at Object.logger._init_loglevel (/Users/matt/Development/Haraka/logger.js:130:28)
    at Object.<anonymous> (/Users/matt/Development/Haraka/logger.js:176:8)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/matt/Development/Haraka/configfile.js:579:10)
```

### Steps to reproduce

Run the above command. Other test files seem to work (e.g. `node run_tests tests/utils.js`)

**Comment by baudehlo** [comment]
For some utterly bizarre reason this appears to now work. I wish I knew why.
