### ISSUE TITLE
Haraka outgoing explodes with URIError: URI malformed

### ISSUE THREAD

**Issue by swerter** [haraka/Haraka#1596]
### Haraka version
2.8.8

### Expected behavior
Send the email out.

### Observed behavior
``` js
2016-09-14T09:37:08.606Z [CRIT] [-] [core] URIError: URI malformed
2016-09-14T09:37:08.606Z [CRIT] [-] [core]     at decodeURIComponent (native)
2016-09-14T09:37:08.606Z [CRIT] [-] [core]     at /home/michael/Documents/Projects/migadu_mail/haraka-outgoing/node_modules/Haraka/mailheader.js:145:17
2016-09-14T09:37:08.606Z [CRIT] [-] [core]     at RegExp.[Symbol.replace] (native)
2016-09-14T09:37:08.607Z [CRIT] [-] [core]     at RegExp.[Symbol.replace] (native)
2016-09-14T09:37:08.607Z [CRIT] [-] [core]     at String.replace (native)
2016-09-14T09:37:08.607Z [CRIT] [-] [core]     at Header.decode_header (/home/michael/Documents/Projects/migadu_mail/haraka-outgoing/node_modules/Haraka/mailheader.js:160:15)
2016-09-14T09:37:08.607Z [CRIT] [-] [core]     at Header._add_header_decode (/home/michael/Documents/Projects/migadu_mail/haraka-outgoing/node_modules/Haraka/mailheader.js:232:20)
2016-09-14T09:37:08.607Z [CRIT] [-] [core]     at /home/michael/Documents/Projects/migadu_mail/haraka-outgoing/node_modules/Haraka/mailheader.js:53:18
2016-09-14T09:37:08.607Z [CRIT] [-] [core]     at Array.forEach (native)
2016-09-14T09:37:08.607Z [CRIT] [-] [core]     at /home/michael/Documents/Projects/migadu_mail/haraka-outgoing/node_modules/Haraka/mailheader.js:52:28
```

### Steps to reproduce

Try to send the following email:

[testemail.txt](https://github.com/haraka/Haraka/files/471799/testemail.txt)

using, for instance, 

    swaks -f aaa@bbb.com -t aaa@bbb.com -s localhost -no-data-fixup -p 2525 -d testemail.txt

**Comment by ScOut3R** [comment]
I see this error as well on incoming emails. Could be at the point when that specific email tries to leave Haraka to the MTA.
The impact is that Haraka is restarted and the connection is dropped, so the message does not reach the backing MTA.

Running Haraka 2.8.8 on Node 6.5.

```javascript
[CRIT] [-] [core] URIError: URI malformed
[CRIT] [-] [core]     at decodeURIComponent (native)
[CRIT] [-] [core]     at /usr/local/lib/node_modules/Haraka/mailheader.js:138:17
[CRIT] [-] [core]     at RegExp.[Symbol.replace] (native)
[CRIT] [-] [core]     at RegExp.[Symbol.replace] (native)
[CRIT] [-] [core]     at String.replace (native)
[CRIT] [-] [core]     at Header.decode_header (/usr/local/lib/node_modules/Haraka/mailheader.js:153:15)
[CRIT] [-] [core]     at Header._add_header_decode (/usr/local/lib/node_modules/Haraka/mailheader.js:225:20)
[CRIT] [-] [core]     at /usr/local/lib/node_modules/Haraka/mailheader.js:51:18
[CRIT] [-] [core]     at Array.forEach (native)
[CRIT] [-] [core]     at /usr/local/lib/node_modules/Haraka/mailheader.js:50:28
[NOTICE] [-] [core] Shutting down
```
