### ISSUE TITLE
rspamd throwing CRIT errors

### ISSUE THREAD

**Issue by msimerson** [haraka/Haraka#1730]
### system info

Haraka | Haraka.js — Version: 2.8.10
 --- | :--- 
Node | v6.9.1
OS | FreeBSD haraka 10.3-RELEASE-p7 FreeBSD 10.3-RELEASE-p7 #0: Thu Aug 11 18:38:15 UTC 2016     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
openssl | OpenSSL 1.0.1s-freebsd  1 Mar 2016

### Expected behavior

rspamd to run without throwing CRIT errors

### Observed behavior

Nov 24 12:13:09 haraka haraka[57387]: [INFO] [E18D51A3-DF22.1] [rspamd] is_spam: true, is_skipped: false, score: 15.8, required_score: 15, action: reject, DBL_SPAM: 6.5, URIBL_BLACK: 7.5, DMARC_NA: 0, RBL_SPAMHAUS_CSS: 2, ONCE_RECEIVED: 0.1, MIME_GOOD: -0.1, R_DKIM_NA: 0, R_SPF_ALLOW: -0.2, messages: (SPF): spf allow
Nov 24 12:13:09 haraka haraka[57387]: [CRIT] [-] [core] TypeError: Cannot read property 'action' of undefined
Nov 24 12:13:09 jails kernel: Nov 24 12:13:09 haraka haraka[57387]: [CRIT] [-] [core] TypeError: Cannot read property 'action' of undefined
Nov 24 12:13:09 haraka haraka[57387]: [CRIT] [-] [core]     at no_reject (/usr/local/lib/node_modules/Haraka/plugins/rspamd.js:175:61)
Nov 24 12:13:09 jails kernel: Nov 24 12:13:09 haraka haraka[57387]: [CRIT] [-] [core]     at no_reject (/usr/local/lib/node_modules/Haraka/plugins/rspamd.js:175:61)
Nov 24 12:13:09 haraka haraka[57387]: [CRIT] [-] [core]     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/Haraka/plugins/rspamd.js:187:57)
Nov 24 12:13:09 jails kernel: Nov 24 12:13:09 haraka haraka[57387]: [CRIT] [-] [core]     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/Haraka/plugins/rspamd.js:187:57)
Nov 24 12:13:09 haraka haraka[57387]: [CRIT] [-] [core]     at emitNone (events.js:91:20)
Nov 24 12:13:09 jails kernel: Nov 24 12:13:09 haraka haraka[57387]: [CRIT] [-] [core]     at emitNone (events.js:91:20)
Nov 24 12:13:09 haraka haraka[57387]: [CRIT] [-] [core]     at IncomingMessage.emit (events.js:185:7)
Nov 24 12:13:09 jails kernel: Nov 24 12:13:09 haraka haraka[57387]: [CRIT] [-] [core]     at IncomingMessage.emit (events.js:185:7)
Nov 24 12:13:09 haraka haraka[57387]: [CRIT] [-] [core]     at endReadableNT (_stream_readable.js:974:12)
Nov 24 12:13:09 jails kernel: Nov 24 12:13:09 haraka haraka[57387]: [CRIT] [-] [core]     at endReadableNT (_stream_readable.js:974:12)
Nov 24 12:13:09 haraka haraka[57387]: [CRIT] [-] [core]     at _combinedTickCallback (internal/process/next_tick.js:74:11)
Nov 24 12:13:09 jails kernel: Nov 24 12:13:09 haraka haraka[57387]: [CRIT] [-] [core]     at _combinedTickCallback (internal/process/next_tick.js:74:11)
Nov 24 12:13:09 haraka haraka[57387]: [CRIT] [-] [core]     at process._tickCallback (internal/process/next_tick.js:98:9)
Nov 24 12:13:09 jails kernel: Nov 24 12:13:09 haraka haraka[57387]: [CRIT] [-] [core]     at process._tickCallback (internal/process/next_tick.js:98:9)

### Steps to reproduce

1. install Haraka from master
2. activate rspamd
3. watch connections

**Comment by msimerson** [comment]
This change was introduced in #1702
