### ISSUE TITLE
tls_socket.js error

### ISSUE THREAD

**Issue by papa-luigi** [haraka/Haraka#1764]
Complete new to Haraka

followed the instructions here: 
https://github.com/haraka/Haraka/wiki/Ubuntu-14.04
  
If i want to start i get this error:

loaded TLD files: 1=1528 2=6049 3=2320
loaded 8184 Public Suffixes

/usr/local/lib/node_modules/Haraka/tls_socket.js:166
    function pseudoTLSServer() {
    ^^^^^^^^
SyntaxError: In strict mode code, functions can only be declared at top level or immediately within another function.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/Haraka/line_socket.js:8:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

### system info
Haraka | Haraka.js — Version: 2.8.12
 --- | :--- 
Node | v0.10.25
OS | Linux haraka 3.13.0-107-generic #154-Ubuntu SMP Tue Dec 20 09:57:27 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.0.1f 6 Jan 2014

TNX for some feedback

**Comment by msimerson** [comment]
Node 0.10 is no longer supported. You need to run at least node 4.
