### ISSUE TITLE
Haraka exits on unhandled exception while processing bad YAML file

### ISSUE THREAD

**Issue by dennisdupont** [haraka/Haraka#1765]
### system info

Haraka | Haraka.js — Version: 2.8.9
 --- | :--- 
Node | v4.6.2
OS | Linux ddupontvm-cnode 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.0.1e-fips 11 Feb 2013

### Expected behavior
Haraka should continue to run when a config file is changed 

### Observed behavior
A syntax error in a YAML file throws an exception.  In configfile.js the exception handler checks for err.code === 'EBADF' otherwise it rethrows the error.

### Steps to reproduce
Contents of my yaml file (errors with the space after the colon in the body regex):  
blacklist:
    - subject: dcdresptest
      body: \nT\[: 0-9 -.\]  DEBUG.*SetError
    - subject: regex2
whitelist:
    - subject: dcdresptest\.1

**Comment by dennisdupont** [comment]
I make the following change:
```    catch (err) {
        if (err.code === 'EBADF') {
            var cache_key = cfreader.get_cache_key(name);
            if (cfreader._config_cache[cache_key]) {
                return cfreader._config_cache[cache_key];
            }
        }
        else {
            logger.logerror('EXCEPTION processing ' + name + ': ' + err);
        }
```

Not sure if this is appropriate in all use cases though, just mine where I can control what the config files are.

**Comment by msimerson** [comment]
What error and code is it emitting? 

Sounds like maybe handling that particular error (just like EBADF) is in order.

**Comment by dennisdupont** [comment]
Here is the log output:
```
2017-01-15T19:06:50.142Z [CRIT] [-] [core] YAMLException: incomplete explicit mapping pair; a key node is missed at line 3, column 21:
2017-01-15T19:06:50.142Z [CRIT] [-] [core]           body: \nT\[0-9: -.\]  DEBUG.*SetError
2017-01-15T19:06:50.143Z [CRIT] [-] [core]                         ^
2017-01-15T19:06:50.143Z [CRIT] [-] [core]     at generateError (/home/ddupont/.nave/installed/4.6.2/lib/node_modules/Haraka/node_modules/js-yaml/lib/js-yaml/loader.js:162:10)
2017-01-15T19:06:50.143Z [CRIT] [-] [core]     at throwError (/home/ddupont/.nave/installed/4.6.2/lib/node_modules/Haraka/node_modules/js-yaml/lib/js-yaml/loader.js:168:9)
2017-01-15T19:06:50.143Z [CRIT] [-] [core]     at readBlockMapping (/home/ddupont/.nave/installed/4.6.2/lib/node_modules/Haraka/node_modules/js-yaml/lib/js-yaml/loader.js:994:9)
2017-01-15T19:06:50.144Z [CRIT] [-] [core]     at composeNode (/home/ddupont/.nave/installed/4.6.2/lib/node_modules/Haraka/node_modules/js-yaml/lib/js-yaml/loader.js:1326:12)
2017-01-15T19:06:50.144Z [CRIT] [-] [core]     at readBlockSequence (/home/ddupont/.nave/installed/4.6.2/lib/node_modules/Haraka/node_modules/js-yaml/lib/js-yaml/loader.js:924:5)
2017-01-15T19:06:50.144Z [CRIT] [-] [core]     at composeNode (/home/ddupont/.nave/installed/4.6.2/lib/node_modules/Haraka/node_modules/js-yaml/lib/js-yaml/loader.js:1325:12)
2017-01-15T19:06:50.144Z [CRIT] [-] [core]     at readBlockMapping (/home/ddupont/.nave/installed/4.6.2/lib/node_modules/Haraka/node_modules/js-yaml/lib/js-yaml/loader.js:1056:11)
2017-01-15T19:06:50.144Z [CRIT] [-] [core]     at composeNode (/home/ddupont/.nave/installed/4.6.2/lib/node_modules/Haraka/node_modules/js-yaml/lib/js-yaml/loader.js:1326:12)
2017-01-15T19:06:50.144Z [CRIT] [-] [core]     at readDocument (/home/ddupont/.nave/installed/4.6.2/lib/node_modules/Haraka/node_modules/js-yaml/lib/js-yaml/loader.js:1488:3)
2017-01-15T19:06:50.145Z [CRIT] [-] [core]     at loadDocuments (/home/ddupont/.nave/installed/4.6.2/lib/node_modules/Haraka/node_modules/js-yaml/lib/js-yaml/loader.js:1544:5)
2017-01-15T19:06:50.146Z [NOTICE] [-] [core] Shutting down
```

and here is js-yaml's exception class (I don't see any code property):
```
function YAMLException(reason, mark) {
  // Super constructor
  Error.call(this);

  // Include stack trace in error object
  if (Error.captureStackTrace) {
    // Chrome and NodeJS
    Error.captureStackTrace(this, this.constructor);
  } else {
    // FF, IE 10+ and Safari 6+. Fallback for others
    this.stack = (new Error()).stack || '';
  }

  this.name = 'YAMLException';
  this.reason = reason;
  this.mark = mark;
  this.message = (this.reason || '(unknown reason)') + (this.mark ? ' ' + this.mark.toString() : '');
}

```

**Comment by msimerson** [comment]
Well that's just ick. I think your change is fine. Please submit it as a PR with the 'fixes #1765' somewhere in the description. Then I'll poke @smfreegard  and make sure he's okay with logging vs throwing the error.

**Comment by msimerson** [comment]
Hi @dennisdupont , still waiting for that PR.

**Comment by dennisdupont** [comment]
Sorry Matt, just been consumed with other issues.  Would I submit this against master?  I don't see a development branch, so I assume you use master for devel and other branches for release.

**Comment by dennisdupont** [comment]
question - this same code is repeated for each of the different config file formats.  Should I apply only to the yaml section?  Doesn't seem to me that any of these should throw an error during reloading a config.

**Comment by msimerson** [comment]
> Would I submit this against master?

Yes.

> Should I apply only to the yaml section?

Yes. 

For a deeper explanation, see [haraka-config](https://github.com/haraka/haraka-config)
