### ISSUE TITLE
Plugin helo.checks failed: TypeError: Cannot read property 'test' of undefined

### ISSUE THREAD

**Issue by ayontulip** [haraka/Haraka#1888]
[CRIT] [A3C84DD0-C9AA-4281-932E-2541CF87DA0E] [core] Plugin helo.checks failed: TypeError: Cannot read property 'test' of undefined
at Plugin.exports.match_re (/haraka/plugins/helo.checks.js:203:27)
at Object.plugins.run_next_hook (/haraka/plugins.js:507:28)
at callback (/haraka/plugins.js:463:32)
at Plugin.exports.init (/haraka/plugins/helo.checks.js:106:16)
at Object.plugins.run_next_hook (/haraka/plugins.js:507:28)
at callback (/haraka/plugins.js:463:32)
at Plugin.exports.proto_mismatch (/haraka/plugins/helo.checks.js:460:45)
at Plugin.exports.proto_mismatch_esmtp (/haraka/plugins/helo.checks.js:479:10)
at Object.plugins.run_next_hook (/haraka/plugins.js:507:28)
at callback (/haraka/plugins.js:463:32)

**Comment by Dexus** [comment]
With out infos about version of haraka we can't help you. Without details i will close this issue in 2 days
