### ISSUE TITLE
auth_proxy socket error

### ISSUE THREAD

**Issue by urlund** [haraka/Haraka#1893]
### Expected behavior
Keep Haraka running when an error occurs in `socket.on('error', function (err) {` (line 75)

I don't know if this would be the correct way to handle it, but it does the trick in my case.
```
socket.on('error', function (err) {
    connection.logerror(self, "connection failed to host " + host + ": " + err);
    socket.end();
    return;
});
```

This gives me:

```
[NOTICE] [FD733108-3B4D-4756-8ED4-A9C507B5937E] [core] connect ip=172.17.0.1 port=44288 local_ip=:: local_port=587
[INFO] [FD733108-3B4D-4756-8ED4-A9C507B5937E] [access] msg:unlisted(conn), fail:invalid domain: NXDOMAIN
[INFO] [FD733108-3B4D-4756-8ED4-A9C507B5937E] [tls] secured: cipher=ECDHE-RSA-AES256-GCM-SHA384 version=TLSv1/SSLv3 verified=false
[INFO] [FD733108-3B4D-4756-8ED4-A9C507B5937E] [core] hook=unrecognized_command plugin=tls function=upgrade_connection params="STARTTLS" retval=OK msg=""
[ERROR] [FD733108-3B4D-4756-8ED4-A9C507B5937E] [auth/auth_proxy] connection failed to host foobar.gmail.com:587: Error: getaddrinfo ENOTFOUND foobar.gmail.com foobar.gmail.com:587
[NOTICE] [FD733108-3B4D-4756-8ED4-A9C507B5937E] [auth/auth_proxy] delaying for 1 seconds
[INFO] [FD733108-3B4D-4756-8ED4-A9C507B5937E] [core] hook=unrecognized_command plugin=auth/auth_proxy function=hook_unrecognized_command params="AUTH" retval=OK msg=""
[ERROR] [FD733108-3B4D-4756-8ED4-A9C507B5937E] [auth/auth_proxy] connection failed to host foobar.gmail.com:587: Error: getaddrinfo ENOTFOUND foobar.gmail.com foobar.gmail.com:587
[NOTICE] [FD733108-3B4D-4756-8ED4-A9C507B5937E] [auth/auth_proxy] delaying for 2 seconds
[INFO] [FD733108-3B4D-4756-8ED4-A9C507B5937E] [core] hook=unrecognized_command plugin=auth/auth_proxy function=hook_unrecognized_command params="AUTH" retval=OK msg=""
[INFO] [FD733108-3B4D-4756-8ED4-A9C507B5937E] [core] hook=unrecognized_command plugin=auth/auth_proxy function=hook_unrecognized_command params="AUTH" retval=OK msg=""
[INFO] [FD733108-3B4D-4756-8ED4-A9C507B5937E] [core] hook=unrecognized_command plugin=auth/auth_proxy function=hook_unrecognized_command params="...yyy..." retval=OK msg=""
[ERROR] [FD733108-3B4D-4756-8ED4-A9C507B5937E] [auth/auth_proxy] connection failed to host foobar.gmail.com:587: Error: getaddrinfo ENOTFOUND foobar.gmail.com foobar.gmail.com:587
[NOTICE] [FD733108-3B4D-4756-8ED4-A9C507B5937E] [auth/auth_proxy] delaying for 4 seconds
[INFO] [FD733108-3B4D-4756-8ED4-A9C507B5937E] [core] hook=unrecognized_command plugin=auth/auth_proxy function=hook_unrecognized_command params="...xxx..." retval=OK msg=""
[INFO] [FD733108-3B4D-4756-8ED4-A9C507B5937E] [core] hook=unrecognized_command plugin=auth/auth_proxy function=hook_unrecognized_command params="AUTH" retval=OK msg=""
[INFO] [FD733108-3B4D-4756-8ED4-A9C507B5937E] [core] hook=unrecognized_command plugin=auth/auth_proxy function=hook_unrecognized_command params="...yyy..." retval=OK msg=""
[ERROR] [FD733108-3B4D-4756-8ED4-A9C507B5937E] [auth/auth_proxy] connection failed to host foobar.gmail.com:587: Error: getaddrinfo ENOTFOUND foobar.gmail.com foobar.gmail.com:587
[NOTICE] [FD733108-3B4D-4756-8ED4-A9C507B5937E] [auth/auth_proxy] delaying for 8 seconds
[INFO] [FD733108-3B4D-4756-8ED4-A9C507B5937E] [core] hook=unrecognized_command plugin=auth/auth_proxy function=hook_unrecognized_command params="...xxx..." retval=OK msg=""
[NOTICE] [FD733108-3B4D-4756-8ED4-A9C507B5937E] [core] disconnect ip=172.17.0.1 rdns="NXDOMAIN" helo="[127.0.0.1]" relay=N early=N esmtp=Y tls=Y pipe=N errors=0 txns=0 rcpts=0/0/0 msgs=0/0/0 bytes=0 lr="535 Authentication failed" time=15.149
```
And Haraka is still running.

### Observed behavior

Current implementation gives me this:

```
[ERROR] [464B11ED-CFC7-47B0-B1CD-CFA81B324165] [auth/auth_proxy] connection failed to host foobar.gmail.com:587: Error: getaddrinfo ENOTFOUND foobar.gmail.com foobar.gmail.com:587
[NOTICE] [464B11ED-CFC7-47B0-B1CD-CFA81B324165] [auth/auth_proxy] delaying for 4 seconds
[NOTICE] [464B11ED-CFC7-47B0-B1CD-CFA81B324165] [auth/auth_proxy] delaying for 8 seconds
[ERROR] [464B11ED-CFC7-47B0-B1CD-CFA81B324165] [core] auth/auth_proxy plugin ran callback multiple times - ignoring subsequent calls
[ERROR] [464B11ED-CFC7-47B0-B1CD-CFA81B324165] [core] Error
    at callback (/usr/local/lib/node_modules/Haraka/plugins.js:450:34)
    at /usr/local/lib/node_modules/Haraka/plugins/auth/auth_base.js:146:28
    at Connection.reset_transaction (/usr/local/lib/node_modules/Haraka/connection.js:627:17)
    at /usr/local/lib/node_modules/Haraka/plugins/auth/auth_base.js:145:28
    at Connection.respond (/usr/local/lib/node_modules/Haraka/connection.js:559:15)
    at Timeout._onTimeout (/usr/local/lib/node_modules/Haraka/plugins/auth/auth_base.js:144:24)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
[DEBUG] [464B11ED-CFC7-47B0-B1CD-CFA81B324165] [core] running unrecognized_command hooks
[CRIT] [-] [core] Error: We are already running hooks! Fatal error!
[CRIT] [-] [core]     at Object.plugins.run_hooks (/usr/local/lib/node_modules/Haraka/plugins.js:403:15)
[CRIT] [-] [core]     at Connection.process_line (/usr/local/lib/node_modules/Haraka/connection.js:340:21)
[CRIT] [-] [core]     at Connection._process_data (/usr/local/lib/node_modules/Haraka/connection.js:465:18)
[CRIT] [-] [core]     at Connection.process_data (/usr/local/lib/node_modules/Haraka/connection.js:375:10)
[CRIT] [-] [core]     at pluggableStream.<anonymous> (/usr/local/lib/node_modules/Haraka/connection.js:135:14)
[CRIT] [-] [core]     at emitOne (events.js:96:13)
[CRIT] [-] [core]     at pluggableStream.emit (events.js:191:7)
[CRIT] [-] [core]     at TLSSocket.<anonymous> (/usr/local/lib/node_modules/Haraka/tls_socket.js:54:14)
[CRIT] [-] [core]     at emitOne (events.js:96:13)
[CRIT] [-] [core]     at TLSSocket.emit (events.js:191:7)
[NOTICE] [-] [core] Shutting down
```

### Steps to reproduce

**auth_proxy.ini**
```
[domains]
example.com = foobar.gmail.com:587
```

**Comment by Dexus** [comment]
this is one correct way to do it
