### ISSUE TITLE
platformDOT not defined in hmal.js

### ISSUE THREAD

**Issue by superman20** [haraka/Haraka#1942]
I received this crash today:
```
[08:06:47] [CRIT] [-] [core] ReferenceError: platformDOT is not defined
[08:06:47] [CRIT] [-] [core]     at split_to_new_recipients (C:\Haraka\npm\node_modules\Haraka\outbound\hmail.js:1272:41)
[08:06:47] [CRIT] [-] [core]     at finish_processing_mail (C:\Haraka\npm\node_modules\Haraka\outbound\hmail.js:582:13)
[08:06:47] [CRIT] [-] [core]     at pluggableStream.<anonymous> (C:\Haraka\npm\node_modules\Haraka\outbound\hmail.js:822:25)
[08:06:47] [CRIT] [-] [core]     at emitOne (events.js:96:13)
[08:06:47] [CRIT] [-] [core]     at pluggableStream.emit (events.js:191:7)
[08:06:47] [CRIT] [-] [core]     at pluggableStream.socket.process_data (C:\Haraka\npm\node_modules\Haraka\line_socket.js:24:20)
[08:06:47] [CRIT] [-] [core]     at pluggableStream.<anonymous> (C:\Haraka\npm\node_modules\Haraka\line_socket.js:35:48)
[08:06:47] [CRIT] [-] [core]     at emitOne (events.js:96:13)
[08:06:47] [CRIT] [-] [core]     at pluggableStream.emit (events.js:191:7)
[08:06:47] [CRIT] [-] [core]     at TLSSocket.<anonymous> (C:\Haraka\npm\node_modules\Haraka\tls_socket.js:54:14)
```
Appears to be a refactoring bug where platformDOT is defined in outbound/index.js and not in hmail.js.  I'd be happy to submit a PR for this.  I assume you'd just want to export platformDOT from index.js?

**Comment by baudehlo** [comment]
I think it probably belongs in qfile.js actually, export it from there into
index.js and hmail.js.

**Comment by msimerson** [comment]
Might it be better to add it to haraka-constants?

**Comment by baudehlo** [comment]
I don't think so. It's not used anywhere but temp file creation in outbound.
