### ISSUE TITLE
Outboud delivery: next() is not defined

### ISSUE THREAD

**Issue by sstevan** [haraka/Haraka#1994]
#### Issue with outbound delivery (splitting #1993)

I'm using http://haraka.github.io/manual/Outbound.html 
to setup outbound delivery. I've made a plugin with copy/paste code
from the tutorial and here's what I'm getting when I run Haraka:
```
[CRIT] [-] [core] TypeError: plugin.loginfo is not a function
```
I don't need logging so when I remove it:

```
[CRIT] [-] [core] ReferenceError: next is not defined
```

What should be included to get `next` in the current scope?

Here's the full output:

```
[CRIT] [-] [core] TypeError: plugin.loginfo is not a function
[CRIT] [-] [core]     at outnext (/etc/haraka/plugins/out.js:29:28)
[CRIT] [-] [core]     at /usr/local/lib/node_modules/Haraka/outbound.js:641:17
[CRIT] [-] [core]     at /usr/local/lib/node_modules/Haraka/node_modules/async/dist/async.js:359:16
[CRIT] [-] [core]     at replenish (/usr/local/lib/node_modules/Haraka/node_modules/async/dist/async.js:876:25)
[CRIT] [-] [core]     at iterateeCallback (/usr/local/lib/node_modules/Haraka/node_modules/async/dist/async.js:866:17)
[CRIT] [-] [core]     at /usr/local/lib/node_modules/Haraka/node_modules/async/dist/async.js:843:16
[CRIT] [-] [core]     at /usr/local/lib/node_modules/Haraka/outbound.js:666:17
[CRIT] [-] [core]     at FSReqWrap.oncomplete (fs.js:135:15)
```
---
```
[CRIT] [-] [core] ReferenceError: next is not defined
[CRIT] [-] [core]     at outnext (/etc/haraka/plugins/out.js:30:21)
[CRIT] [-] [core]     at /usr/local/lib/node_modules/Haraka/outbound.js:641:17
[CRIT] [-] [core]     at /usr/local/lib/node_modules/Haraka/node_modules/async/dist/async.js:359:16
[CRIT] [-] [core]     at replenish (/usr/local/lib/node_modules/Haraka/node_modules/async/dist/async.js:876:25)
[CRIT] [-] [core]     at iterateeCallback (/usr/local/lib/node_modules/Haraka/node_modules/async/dist/async.js:866:17)
[CRIT] [-] [core]     at /usr/local/lib/node_modules/Haraka/node_modules/async/dist/async.js:843:16
[CRIT] [-] [core]     at /usr/local/lib/node_modules/Haraka/outbound.js:666:17
[CRIT] [-] [core]     at FSReqWrap.oncomplete (fs.js:135:15)
```
---
#### Haraka

Stack | Version
------|---------
Haraka | Haraka.js — Version: 2.8.13
Node | v8.0.0
OS | Ubuntu 16.04
openssl | OpenSSL 1.0.2g  1 Mar 2016

**Comment by baudehlo** [comment]
That `next()` function is the next from your hook. You can only use that
code within the body of an existing hook.

**Comment by sstevan** [comment]
Got it. Thanks!  I've found working example.
