### ISSUE TITLE
Auth plugin fails when already authenticating

### ISSUE THREAD

**Issue by gramakri** [haraka/Haraka#1999]
### system info

Using Haraka from master

### Steps to reproduce
* `openssl s_client -starttls smtp -crlf -connect mymailserver.com:587`
* Send the following commands:
  * `EHLO openssl.client.net`
  * `AUTH LOGIN Z2lyaXNo`
  * `AUTH LOGIN`

The above causes the auth plugin to fail as:
```
[CRIT] [E4D763CD-C2E8-4AD5-84C4-BBDC1AE90317] [core] Plugin cloudron failed: TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at fromObject (buffer.js:262:9)
    at Function.Buffer.from (buffer.js:101:10)
    at new Buffer (buffer.js:80:17)
    at Object.exports.unbase64 (/app/haraka/node_modules/haraka-utils/index.js:268:12)
    at Plugin.exports.auth_login (/app/haraka/plugins/auth/auth_base.js:230:19)
    at Plugin.exports.select_auth_method (/app/haraka/plugins/auth/auth_base.js:177:21)
    at Plugin.exports.hook_unrecognized_command (/app/haraka/plugins/auth/auth_base.js:32:23)
    at Object.plugins.run_next_hook (/app/haraka/plugins.js:506:28)
    at callback (/app/haraka/plugins.js:462:32)
    at Plugin.exports.upgrade_connection (/app/haraka/plugins/tls.js:189:56)
```

**Comment by gramakri** [comment]
Core of the issue is that the select_auth_method is called again in the second method and it calls the `auth_login` method for the second AUTH call. The function then decides to decode the `undefined` value and fails.
