### ISSUE TITLE
outbound CRIT error

### ISSUE THREAD

**Issue by msimerson** [haraka/Haraka#2031]
### system info

Haraka | Haraka.js — Version: 2.8.14
 --- | :--- 
Node | v6.11.1
OS | FreeBSD haraka 10.3-RELEASE-p18 FreeBSD 10.3-RELEASE-p18 #0: Tue Apr 11 10:31:00 UTC 2017     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
openssl | OpenSSL 1.0.1s-freebsd  1 Mar 2016
### Expected behavior

No crash.

### Observed behavior

````
Jul 31 09:29:57 nictool nt_export: nsid 29 has 60760 zones, 0 changed, exiting
Jul 31 09:29:57 haraka haraka: [ERROR] [-] [core] [outbound] Failed to get pool entry: Outbound connection timed out to 217.146.76.20:25
Jul 31 09:29:57 haraka haraka: [INFO] [C2E9682F-E908-4A07-B685-28C17EFD9A6F.1.2] [outbound] Temp failing 1501517405311_1501518231320_4_94595_VoZOxO_2_haraka for 1024 seconds: Tried all MXs
Jul 31 09:29:57 haraka haraka: [ERROR] [C2E9682F-E908-4A07-B685-28C17EFD9A6F.1.2] [outbound] Remote end 217.146.76.20:25 closed connection while we were processing mail. Trying next MX.
Jul 31 09:29:57 haraka haraka: [INFO] [C2E9682F-E908-4A07-B685-28C17EFD9A6F.1.2] [outbound] Temp failing 1501517405311_1501519621782_5_94595_VoZOxO_7_haraka for 2048 seconds: Tried all MXs
Jul 31 09:29:57 haraka haraka: [CRIT] [-] [core] Error: Callback was already called.
Jul 31 09:29:57 jails kernel: Jul 31 09:29:57 haraka haraka: [CRIT] [-] [core] Error: Callback was already called.
Jul 31 09:29:57 haraka haraka: [CRIT] [-] [core]     at /usr/local/lib/node_modules/Haraka/node_modules/async/dist/async.js:903:32
Jul 31 09:29:57 jails kernel: Jul 31 09:29:57 haraka haraka: [CRIT] [-] [core]     at /usr/local/lib/node_modules/Haraka/node_modules/async/dist/async.js:903:32
Jul 31 09:29:57 haraka haraka: [CRIT] [-] [core]     at HMailItem.hmail.next_cb (/usr/local/lib/node_modules/Haraka/outbound/queue.js:41:9)
Jul 31 09:29:57 jails kernel: Jul 31 09:29:57 haraka haraka: [CRIT] [-] [core]     at HMailItem.hmail.next_cb (/usr/local/lib/node_modules/Haraka/outbound/queue.js:41:9)
Jul 31 09:29:57 haraka haraka: [CRIT] [-] [core]     at /usr/local/lib/node_modules/Haraka/outbound/hmail.js:1268:15
Jul 31 09:29:57 jails kernel: Jul 31 09:29:57 haraka haraka: [CRIT] [-] [core]     at /usr/local/lib/node_modules/Haraka/outbound/hmail.js:1268:15
Jul 31 09:29:57 haraka haraka: [CRIT] [-] [core]     at FSReqWrap.oncomplete (fs.js:123:15)
Jul 31 09:29:57 jails kernel: Jul 31 09:29:57 haraka haraka: [CRIT] [-] [core]     at FSReqWrap.oncomplete (fs.js:123:15)
Jul 31 09:29:57 haraka haraka: [NOTICE] [-] [core] Shutting down
Jul 31 09:29:57 haraka haraka: [NOTICE] [-] [core] worker 2 exited with error code: 1
Jul 31 09:29:58 haraka haraka: [NOTICE] [-] [core] worker 3 started pid=2832
````

### Steps to reproduce

1. Install Haraka
2. send an email to matt@wildduck.email

**Comment by msimerson** [comment]
Duplicate of #2030
