### ISSUE TITLE
Crash when sending "AUTH LOGIN" in already authenticated connection

### ISSUE THREAD

**Issue by gramakri** [haraka/Haraka#2038]
### system info

Node 8, haraka master as of today

### Expected behavior

```
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at Function.Buffer.from (buffer.js:179:11)
    at new Buffer (buffer.js:154:17)
    at Object.exports.unbase64 (/home/girish/tmp/Haraka/node_modules/haraka-utils/index.js:268:12)
    at Plugin.exports.auth_login (auth/auth_base:232:19)
    at Plugin.exports.select_auth_method (auth/auth_base:179:21)
    at Plugin.exports.hook_unrecognized_command (auth/auth_base:32:23)
    at Object.<anonymous> (/home/girish/tmp/Haraka/tests/plugins/auth/auth_base.js:330:25)
    at auth/auth_base:119:24
    at Connection.obj.respond (/home/girish/tmp/Haraka/node_modules/haraka-test-fixtures/lib/connection.js:37:55)
    at passwd_ok (auth/auth_base:113:24)
    at callback (auth/auth_base:54:16)
    at Plugin.plugin.get_plain_passwd (/home/girish/tmp/Haraka/tests/plugins/auth/auth_base.js:11:37)
    at Plugin.exports.check_plain_passwd (auth/auth_base:57:14)
    at Plugin.exports.check_user (auth/auth_base:153:16)
    at Plugin.exports.auth_login (auth/auth_base:234:23)
    at Plugin.exports.hook_unrecognized_command (auth/auth_base:42:23)
```

### Observed behavior

Should not crash

### Steps to reproduce
* `openssl s_client -starttls smtp -crlf -connect mymailserver.com:587`
* Send the following commands:
  * `EHLO openssl.client.net`
  * `AUTH LOGIN Z2lyaXNo`
  * Send base64 password
  * `AUTH LOGIN`

**Comment by msimerson** [comment]
This triggered a memory of #1999. They seem very related?

**Comment by msimerson** [comment]
And to help us understand, why would a remote authenticate again, after having succeeded at authenticating?

**Comment by gramakri** [comment]
@msimerson I don't know why the client is sending auth again after succeeding authentication. I think both the bugs are triggered by some buggy client (or maybe some malicious client).

I only have the backtrace to work with, so I am working my way back from them (https://git.cloudron.io/cloudron/box/issues/400 in this case).

If anything, these fixes only make haraka more resilient against buggy clients.

**Comment by msimerson** [comment]
> these fixes only make haraka more resilient

touché. And even in edge cases like this, crashing certainly isn't The Right Thing. ;-)
