### ISSUE TITLE
SyntaxError on the first run

### ISSUE THREAD

**Issue by rdeavila** [haraka/Haraka#2132]
### system info

```
ubuntu@ip-172-31-37-174:~$ echo "Haraka | $(haraka -v)"; echo " --- | :--- "; echo "Node | $(node -v)"; echo "OS | $(uname -a)"; echo "openssl | $(openssl version)"
/usr/local/lib/node_modules/Haraka/bin/haraka:93
    let plist = dir + "\n";
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
Haraka |
 --- | :---
Node | v4.2.6
OS | Linux ip-172-31-37-174 4.4.0-1022-aws #31-Ubuntu SMP Tue Jun 27 11:27:55 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.0.2g  1 Mar 2016
ubuntu@ip-172-31-37-174:~$
```

### Expected behavior

Run the system

### Observed behavior

```
/usr/local/lib/node_modules/Haraka/bin/haraka:93
    let plist = dir + "\n";
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
``` 

### Steps to reproduce

* Follow the [Ubuntu 14.04 install](https://github.com/haraka/Haraka/wiki/Ubuntu-14.04)
* Stuck on `haraka -i /etc/haraka`

The same problem happens when I try to run this on Docker, using the `Dockerfile` of the `master` branch.

**Comment by KingNoosh** [comment]
You need to be on node 6, 4 isn't supported anymore.

**Comment by KingNoosh** [comment]
Run:
```bash
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs
```

**Comment by rdeavila** [comment]
Thank you... this works. I'll try to write a PR to change this [on `Dockerfile`](https://github.com/haraka/Haraka/blob/master/Dockerfile#L25) too.
