### ISSUE TITLE
TypeError: Method get TypedArray.prototype.length called on incompatible receiver

### ISSUE THREAD

**Issue by KingNoosh** [haraka/Haraka#2201]
### system info

Haraka | Haraka.js — Version: 2.8.15
 --- | :---
Node | v6.11.4
OS | Linux REDACTED_HOSTNAME 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.0.2g  1 Mar 2016

### Expected behavior
Not to crash

### Observed behavior
Server crased with the following error
```
2017-10-05T09:30:57.064Z level=CRIT uuid=- origin=core message="TypeError: Method get TypedArray.prototype.length called on incompatible receiver [object Object]"
2017-10-05T09:30:57.064Z level=CRIT uuid=- origin=core message="    at Buffer.get length [as length] (native)"
2017-10-05T09:30:57.064Z level=CRIT uuid=- origin=core message="    at Buffer.toString (buffer.js:490:36)"
2017-10-05T09:30:57.064Z level=CRIT uuid=- origin=core message="    at Body.events.EventEmitter.Body.try_iconv (/usr/src/app/node_modules/Haraka/mailbody.js:326:29)"
2017-10-05T09:30:57.065Z level=CRIT uuid=- origin=core message="    at Body.events.EventEmitter.Body.parse_end (/usr/src/app/node_modules/Haraka/mailbody.js:311:10)"
2017-10-05T09:30:57.065Z level=CRIT uuid=- origin=core message="    at Body.events.EventEmitter.Body.parse_child (/usr/src/app/node_modules/Haraka/mailbody.js:56:55)"
2017-10-05T09:30:57.065Z level=CRIT uuid=- origin=core message="    at Body.events.EventEmitter.Body.parse_more (/usr/src/app/node_modules/Haraka/mailbody.js:49:39)"
2017-10-05T09:30:57.065Z level=CRIT uuid=- origin=core message="    at Transaction.add_data (/usr/src/app/node_modules/Haraka/transaction.js:106:34)"
2017-10-05T09:30:57.065Z level=CRIT uuid=- origin=core message="    at Connection.accumulate_data (/usr/src/app/node_modules/Haraka/connection.js:1658:22)"
2017-10-05T09:30:57.065Z level=CRIT uuid=- origin=core message="    at Connection.process_line (/usr/src/app/node_modules/Haraka/connection.js:313:14)"
2017-10-05T09:30:57.065Z level=CRIT uuid=- origin=core message="    at Connection._process_data (/usr/src/app/node_modules/Haraka/connection.js:496:18)"
2017-10-05T09:30:57.066Z level=NOTICE uuid=- origin=core message="Shutting down"
```

### Steps to reproduce
Unknown

**Comment by Chopinsky** [comment]
Culprit seems to be from this line:

https://github.com/haraka/Haraka/blob/6db416fc1a86b03cab6ec5d38584a2b5ede8ba5c/mailbody.js#L225

Somehow the buffer object isn't initialized correctly (or is null?), which then cause the crash because the length property getter doesn't exist on the object, from this line:

https://github.com/nodejs/node/blob/3701b0230961644186fbc4ea2d6ef978601ac0f6/lib/buffer.js#L647

Very weird issue, not sure this is a bug for Node or Haraka.

**Comment by msimerson** [comment]
Since we're not sure and no activity in a year, I'm closing this. It doesn't seem likely but if "Somehow the buffer object isn't initialized correctly" is the underlying issue, #2553 might help.
