### ISSUE TITLE
Haraka crashes when write after end

### ISSUE THREAD

**Issue by KingNoosh** [haraka/Haraka#2202]
### system info
Haraka | Haraka.js — Version: 2.8.15
 --- | :---
Node | v6.11.4
OS | Linux REDACTED_HOSTNAME 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.0.2g  1 Mar 2016

### Expected behavior
Not to crash

### Observed behavior
```
2017-10-04T07:45:56.306Z level=ERROR uuid=4B593AD4-A93D-4536-8A75-1FFC205E806C.1 origin=outbound message="Ongoing connection failed to 213.199.154.170:25 : Error: write after end"
2017-10-04T07:45:56.308Z level=CRIT uuid=- origin=core message="Error: write after end"
2017-10-04T07:45:56.308Z level=CRIT uuid=- origin=core message="    at writeAfterEnd (_stream_writable.js:193:12)"
2017-10-04T07:45:56.308Z level=CRIT uuid=- origin=core message="    at Socket.Writable.write (_stream_writable.js:240:5)"
2017-10-04T07:45:56.308Z level=CRIT uuid=- origin=core message="    at Socket.write (net.js:657:40)"
2017-10-04T07:45:56.308Z level=CRIT uuid=- origin=core message="    at pluggableStream.stream.Stream.pluggableStream.write (/usr/src/app/node_modules/Haraka/tls_socket.js:112:34)"
2017-10-04T07:45:56.308Z level=CRIT uuid=- origin=core message="    at Object.destroy (/usr/src/app/node_modules/Haraka/outbound/client_pool.js:75:24)"
2017-10-04T07:45:56.308Z level=CRIT uuid=- origin=core message="    at Pool.destroy (/usr/src/app/node_modules/generic-pool/lib/generic-pool.js:196:17)"
2017-10-04T07:45:56.308Z level=CRIT uuid=- origin=core message="    at sockend (/usr/src/app/node_modules/Haraka/outbound/client_pool.js:171:37)"
2017-10-04T07:45:56.308Z level=CRIT uuid=- origin=core message="    at Object.exports.release_client (/usr/src/app/node_modules/Haraka/outbound/client_pool.js:140:16)"
2017-10-04T07:45:56.308Z level=CRIT uuid=- origin=core message="    at pluggableStream.<anonymous> (/usr/src/app/node_modules/Haraka/outbound/hmail.js:410:25)"
2017-10-04T07:45:56.308Z level=CRIT uuid=- origin=core message="    at pluggableStream.g (events.js:292:16)"
```

### Steps to reproduce
Not sure

**Comment by mtrivera** [comment]
Do you remember how you installed it? Git or npm?

**Comment by msimerson** [comment]
looks like the same issue as #1576

**Comment by msimerson** [comment]
Closing as duplicate.
