### ISSUE TITLE
TypeError: Path must be a string. Received NaN

### ISSUE THREAD

**Issue by rc111** [haraka/Haraka#2257]
### system info

Please report my OS is ubuntu , Node version is v8.7.0, and Haraka version is Haraka.js — Version: 2.8.16 by running this shell script on your Haraka server and replacing this section with the output.

Haraka | Haraka.js — Version: 2.8.16
 --- | :--- 
Node | v8.7.0
OS | Linux vps149890.vps.ovh.ca 2.6.32-696.13.2.el6.x86_64 #1 SMP Thu Oct 5 21:22:16 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.0.1e-fips 11 Feb 2013
 
### Expected behavior
I need to worked my Haraka mail server by configure the plugin:
loglevel: INFO
log format: DEFAULT
Starting up Haraka version 2.8.16
[INFO] [-] [core] Loading plugins
[INFO] [-] [core] Loading plugin: auth/flat_file
[INFO] [-] [core] Loading plugin: spf
[INFO] [-] [core] Loading plugin: dkim_sign
[INFO] [-] [core] Loading plugin: queue/smtp_forward
[NOTICE] [-] [core] Listening on 162.52.22.54:587
[INFO] [-] [core] [outbound] Loading outbound queue from /etc/haraka/queue

My spf and dkim signature is not sended to the sender mail. expected behavior is to configure dkim and spf on server properly .

### Observed behavior
[NOTICE] [C992E032-519C-4144-A3BC-5D1EE1CAB131.1] [core] message size=607 rcpts=1/0/0 delay=0.468 code=CONT msg=""
[CRIT] [C992E032-519C-4144-A3BC-5D1EE1CAB131.1] [core] Plugin dkim_sign failed: TypeError: Path must be a string. Received NaN
    at assertPath (path.js:28:11)
    at Object.resolve (path.js:1188:7)
    at Plugin.exports.get_key_dir (/usr/lib/node_modules/Haraka/plugins/dkim_sign.js:231:28)
    at Plugin.exports.hook_queue_outbound.exports.hook_pre_send_trans_email (/usr/lib/node_modules/Haraka/plugins/dkim_sign.js:174:12)
    at Object.plugins.run_next_hook (/usr/lib/node_modules/Haraka/plugins.js:506:28)
    at Object.plugins.run_hooks (/usr/lib/node_modules/Haraka/plugins.js:421:13)
    at Connection.data_post_respond (/usr/lib/node_modules/Haraka/connection.js:1749:25)
    at callback (/usr/lib/node_modules/Haraka/plugins.js:479:35)
    at Object.plugins.run_next_hook (/usr/lib/node_modules/Haraka/plugins.js:506:28)

[CRIT] [-] [core] Plugin dkim_sign failed: TypeError: Path must be a string. Received NaN
    at assertPath (path.js:28:11)
    at Object.resolve (path.js:1188:7)
    at Plugin.exports.get_key_dir (/usr/lib/node_modules/Haraka/plugins/dkim_sign.js:231:28)
    at Plugin.exports.hook_queue_outbound.exports.hook_pre_send_trans_email (/usr/lib/node_modules/Haraka/plugins/dkim_sign.js:174:12)
    at Object.plugins.run_next_hook (/usr/lib/node_modules/Haraka/plugins.js:506:28)
    at Object.plugins.run_hooks (/usr/lib/node_modules/Haraka/plugins.js:421:13)
    at Object.exports.send_trans_email (/usr/lib/node_modules/Haraka/outbound/index.js:277:13)
    at Object.exports.send_email (/usr/lib/node_modules/Haraka/outbound/index.js:72:21)
    at Connection.queue_outbound_respond (/usr/lib/node_modules/Haraka/connection.js:1843:22)
    at callback (/usr/lib/node_modules/Haraka/plugins.js:479:35)

### Steps to reproduce
First i configure the authentication of haraka and then configure the dkim and spf plugins .

I also update the npm ,  version problem is the issue of it ?.
Path is an dkim_sign.ini location or any headers location?.
is it any preserved structure which needs to stay unchanged?
and in the dkim_sign.js file an variable called "keydir" makes confused , don't understand where is is contain the values , becuase it is not mentioned in any file?

Thank you.

**Comment by KingNoosh** [comment]
Resolved within IRC, OP copied dkim_sign.js and made their own changes with syntax errors.
