### ISSUE TITLE
Haraka crash on specific mail

### ISSUE THREAD

**Issue by Infern1** [haraka/Haraka#2284]
### system info

```
Haraka | Haraka.js — Version: 2.8.16
 --- | :---
Node | v6.11.5
OS | FreeBSD haraka 10.3-RELEASE-p20 FreeBSD 10.3-RELEASE-p20 #0: Wed Jul 12 03:13:07 UTC 2017     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
openssl | OpenSSL 1.0.1s-freebsd  1 Mar 2016
```
### Expected behavior
no crash on mail

### Observed behavior

Crash of Haraka and restart of Haraka continously. Removed this mail from the queue and works again as normal, mail file available on request

```
2017-11-01T07:31:27.828Z [DEBUG] [-] [dnsbl] looking up: 2.0.0.127.bl.spamcop.net.
2017-11-01T07:31:27.831Z [INFO] [-] [core] [outbound] Done fixing up old PID queue files
2017-11-01T07:31:27.831Z [INFO] [-] [core] [outbound] 0 files in my delivery queue
2017-11-01T07:31:27.831Z [INFO] [-] [core] [outbound] 1 files in my load queue
2017-11-01T07:31:27.831Z [INFO] [-] [core] [outbound] 0 files in my temp fail queue
2017-11-01T07:31:27.846Z [INFO] [-] [karma] connected to redis://172.16.15.16:6379/3 v3.2.10
2017-11-01T07:31:27.846Z [DEBUG] [-] [server]  hook=init_child plugin=karma function=init_redis_plugin params="" retval=CONT msg=""
2017-11-01T07:31:27.847Z [DEBUG] [-] [server] running init_child hook in watch plugin
2017-11-01T07:31:27.860Z [DEBUG] [-] [watch] psubscribed to result-*
2017-11-01T07:31:27.860Z [DEBUG] [-] [server]  hook=init_child plugin=watch function=redis_subscribe_all_results params="" retval=CONT msg=""
2017-11-01T07:31:27.861Z [DEBUG] [-] [server] running init_child hook in redis plugin
2017-11-01T07:31:27.867Z [DEBUG] [-] [outbound] todo header length: 2061
2017-11-01T07:31:27.874Z [CRIT] [-] [core] Error: Uncaught, unspecified "error" event. (invalid todo header end char: 1 at pos 2061 of 1508843726714_1508843726714_0_57634_tJmDld_1_haraka)
2017-11-01T07:31:27.874Z [CRIT] [-] [core]     at HMailItem.emit (events.js:163:17)
2017-11-01T07:31:27.874Z [CRIT] [-] [core]     at ReadStream.todo_json_stream.on (/usr/local/lib/node_modules/Haraka/outbound/hmail.js:116:30)
2017-11-01T07:31:27.874Z [CRIT] [-] [core]     at emitNone (events.js:91:20)
2017-11-01T07:31:27.874Z [CRIT] [-] [core]     at ReadStream.emit (events.js:185:7)
2017-11-01T07:31:27.874Z [CRIT] [-] [core]     at endReadableNT (_stream_readable.js:974:12)
2017-11-01T07:31:27.875Z [CRIT] [-] [core]     at _combinedTickCallback (internal/process/next_tick.js:80:11)
2017-11-01T07:31:27.875Z [CRIT] [-] [core]     at process._tickCallback (internal/process/next_tick.js:104:9)
2017-11-01T07:31:27.876Z [NOTICE] [-] [core] Shutting down
2017-11-01T07:31:27.883Z [NOTICE] [-] [core] worker 50 exited with error code: 1
2017-11-01T07:31:27.962Z [NOTICE] [-] [core] worker started worker=51 pid=57635
```

**Comment by baudehlo** [comment]
I think this is likely fixed by #2238

**Comment by Infern1** [comment]
Installed the latest version, let's check

**Comment by Infern1** [comment]
Sender did send the mail again and haraka did not crash
