### ISSUE TITLE
Unrecognized Command failure

### ISSUE THREAD

**Issue by smfreegard** [haraka/Haraka#2378]
Putting this here so I don't forget about it:

`````
3/27/2018 2:44:39 PM[CRIT] [C5B3571A-110A-4942-8A47-DEB528847811] [core] Plugin auth_trap failed: TypeError: /^([^ ]*)( +(.*))?$/.exec is not a function or its return value is not iterable
3/27/2018 2:44:39 PM    at Connection.process_line (/usr/local/lib/node_modules/Haraka/connection.js:315:77)
3/27/2018 2:44:39 PM    at Connection._process_data (/usr/local/lib/node_modules/Haraka/connection.js:464:22)
3/27/2018 2:44:39 PM    at Connection.respond (/usr/local/lib/node_modules/Haraka/connection.js:561:14)
3/27/2018 2:44:39 PM    at Connection.unrecognized_command_respond (/usr/local/lib/node_modules/Haraka/connection.js:750:22)
3/27/2018 2:44:39 PM    at callback (/usr/local/lib/node_modules/Haraka/plugins.js:480:35)
3/27/2018 2:44:39 PM    at Plugin.exports.hook_unrecognized_command (/usr/local/lib/node_modules/Haraka/plugins/auth/auth_base.js:35:52)
3/27/2018 2:44:39 PM    at Object.plugins.run_next_hook (/usr/local/lib/node_modules/Haraka/plugins.js:505:28)
3/27/2018 2:44:39 PM    at callback (/usr/local/lib/node_modules/Haraka/plugins.js:463:32)
3/27/2018 2:44:39 PM    at Plugin.exports.upgrade_connection (/usr/local/lib/node_modules/Haraka/plugins/tls.js:90:44)
3/27/2018 2:44:39 PM    at Object.plugins.run_next_hook (/usr/local/lib/node_modules/Haraka/plugins.js:505:28)
`````

No idea what is causing RegExp.exec() to return 'not a function' yet...

**Comment by msimerson** [comment]
Moved to [wiki](https://github.com/haraka/Haraka/wiki)

**Comment by msimerson** [comment]
Another option would be creating an auth-trip plugin. I could set up the repo if you'd like, and then we can transfer this issue to that repo.
