### ISSUE TITLE
Outbound crash when no SSL/TLS certificates present

### ISSUE THREAD

**Issue by smfreegard** [haraka/Haraka#2392]
### system info

Haraka github master
Node | v8.11.1
OS | Linux ubuntu 4.13.0-32-generic #35-Ubuntu SMP Thu Jan 25 09:13:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.0.2g  1 Mar 2016

### Expected behavior

To handle when no TLS certificates are present (e.g. development machine)

### Observed behavior

`````
[DEBUG] [4219F97A-8218-4974-9049-BC0231A806C6.1.1] [outbound] running send_email hooks
[DEBUG] [4219F97A-8218-4974-9049-BC0231A806C6.1.1] [outbound] Sending mail: 1523665132170_1523665132170_0_7996_2SmsZC_1_ubuntu
[DEBUG] [4219F97A-8218-4974-9049-BC0231A806C6.1.1] [outbound] running get_mx hooks
[INFO] [4219F97A-8218-4974-9049-BC0231A806C6.1.1] [outbound] Looking up A records for: mail1-ewh.fsl.com
[INFO] [4219F97A-8218-4974-9049-BC0231A806C6.1.1] [outbound] Attempting to deliver to: 69.63.143.51:25 (0) (0)
[INFO] [-] [core] [outbound] [outbound::25:69.63.143.51:undefined:50] dispense() clients=1 available=0
[DEBUG] [-] [core] [outbound] [outbound::25:69.63.143.51:undefined:50] createResource() - creating obj - count=1 min=0 max=10
[DEBUG] [-] [core] [outbound] created uuid=DC9C6BCD-41BB-4C20-9C06-6590DD18FC54 host=69.63.143.51 port=25 pool_timeout=50
[INFO] [-] [core] [outbound] acquired socket DC9C6BCD-41BB-4C20-9C06-6590DD18FC54 for outbound::25:69.63.143.51:undefined:50
[PROTOCOL] [4219F97A-8218-4974-9049-BC0231A806C6.1.1] [outbound] S: 220 mail1-ewh.fsl.com ESMTP DefenderMX 2.7.3 ready (05DDFD74-C9EC-4E1E-9CA1-4BB89DC7D1F1)\r\n
[PROTOCOL] [4219F97A-8218-4974-9049-BC0231A806C6.1.1] [outbound] C: EHLO home.stevefreegard.com
[PROTOCOL] [4219F97A-8218-4974-9049-BC0231A806C6.1.1] [outbound] S: 250-mail1-ewh.fsl.com Hello home.freegard.name [82.69.13.196]\r\n
[PROTOCOL] [4219F97A-8218-4974-9049-BC0231A806C6.1.1] [outbound] S: 250-PIPELINING\r\n
[PROTOCOL] [4219F97A-8218-4974-9049-BC0231A806C6.1.1] [outbound] S: 250-8BITMIME\r\n
[PROTOCOL] [4219F97A-8218-4974-9049-BC0231A806C6.1.1] [outbound] S: 250-SIZE 52428800\r\n
[PROTOCOL] [4219F97A-8218-4974-9049-BC0231A806C6.1.1] [outbound] S: 250-STARTTLS\r\n
[PROTOCOL] [4219F97A-8218-4974-9049-BC0231A806C6.1.1] [outbound] S: 250 XCLIENT NAME ADDR PROTO HELO LOGIN\r\n
[PROTOCOL] [4219F97A-8218-4974-9049-BC0231A806C6.1.1] [outbound] C: STARTTLS
[PROTOCOL] [4219F97A-8218-4974-9049-BC0231A806C6.1.1] [outbound] S: 220 Go ahead.\r\n
[INFO] [-] [core] loading tls.ini
[DEBUG] [-] [core] loading dhparams from dhparams.pem
[ERROR] [-] [core] tls key tls_key.pem could not be loaded.
[ERROR] [-] [core] Config {
  root_path: '/home/smf/git/Haraka/config',
  module_config: [Function],
  overrides_path: '/home/smf/git/Haraka/config' }
[ERROR] [-] [core] tls cert tls_cert.pem could not be loaded.
[CRIT] [-] [core] TypeError: Cannot read property 'passphrase' of null
[CRIT] [-] [core]     at Object.createSecureContext (_tls_common.js:100:32)
[CRIT] [-] [core]     at new exports.connect (_tls_wrap.js:1049:48)
[CRIT] [-] [core]     at pluggableStream.socket.upgrade (/home/smf/git/Haraka/tls_socket.js:672:27)
[CRIT] [-] [core]     at pluggableStream.<anonymous> (/home/smf/git/Haraka/outbound/hmail.js:754:36)
[CRIT] [-] [core]     at emitOne (events.js:116:13)
[CRIT] [-] [core]     at pluggableStream.emit (events.js:211:7)
[CRIT] [-] [core]     at pluggableStream.on_socket_data (/home/smf/git/Haraka/line_socket.js:25:20)
[CRIT] [-] [core]     at emitOne (events.js:116:13)
[CRIT] [-] [core]     at pluggableStream.emit (events.js:211:7)
[CRIT] [-] [core]     at Socket.<anonymous> (/home/smf/git/Haraka/tls_socket.js:59:18)
[NOTICE] [-] [core] Shutting down
`````

### Steps to reproduce

Install and start Haraka, send a message that outbound will relay to an external host that advertises STARTTLS and it will crash.

**Comment by smfreegard** [comment]
To be more clear.  We shouldn't need a TLS certificate for this to work.  We're acting as the client in this case, so there is no requirement to present a certificate.

**Comment by msimerson** [comment]
Just ran across #1340 which is related.
