### ISSUE TITLE
PR #2250 Issues

### ISSUE THREAD

**Issue by smfreegard** [haraka/Haraka#2398]
#2250 is causing some weird issues that I'm having trouble tracking down.

`````
3/27/2018 2:44:39 PM[CRIT] [C5B3571A-110A-4942-8A47-DEB528847811] [core] Plugin auth_trap failed: TypeError: /^([^ ]*)( +(.*))?$/.exec is not a function or its return value is not iterable
3/27/2018 2:44:39 PM    at Connection.process_line (/usr/local/lib/node_modules/Haraka/connection.js:315:77)
3/27/2018 2:44:39 PM    at Connection._process_data (/usr/local/lib/node_modules/Haraka/connection.js:464:22)
3/27/2018 2:44:39 PM    at Connection.respond (/usr/local/lib/node_modules/Haraka/connection.js:561:14)
3/27/2018 2:44:39 PM    at Connection.unrecognized_command_respond (/usr/local/lib/node_modules/Haraka/connection.js:750:22)
3/27/2018 2:44:39 PM    at callback (/usr/local/lib/node_modules/Haraka/plugins.js:480:35)
3/27/2018 2:44:39 PM    at Plugin.exports.hook_unrecognized_command (/usr/local/lib/node_modules/Haraka/plugins/auth/auth_base.js:35:52)
3/27/2018 2:44:39 PM    at Object.plugins.run_next_hook (/usr/local/lib/node_modules/Haraka/plugins.js:505:28)
3/27/2018 2:44:39 PM    at callback (/usr/local/lib/node_modules/Haraka/plugins.js:463:32)
3/27/2018 2:44:39 PM    at Plugin.exports.upgrade_connection (/usr/local/lib/node_modules/Haraka/plugins/tls.js:90:44)
3/27/2018 2:44:39 PM    at Object.plugins.run_next_hook (/usr/local/lib/node_modules/Haraka/plugins.js:505:28)
`````

and

`````
4/18/2018 6:31:25 PM[CRIT] [E28E7A65-B41C-4A69-B835-6E5716E10C30] [core] Plugin auth_trap failed: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of null
4/18/2018 6:31:25 PM    at Connection.process_line (/usr/local/lib/node_modules/Haraka/connection.js:315:77)
4/18/2018 6:31:25 PM    at Connection._process_data (/usr/local/lib/node_modules/Haraka/connection.js:464:22)
4/18/2018 6:31:25 PM    at Connection.respond (/usr/local/lib/node_modules/Haraka/connection.js:561:14)
4/18/2018 6:31:25 PM    at Connection.unrecognized_command_respond (/usr/local/lib/node_modules/Haraka/connection.js:750:22)
4/18/2018 6:31:25 PM    at callback (/usr/local/lib/node_modules/Haraka/plugins.js:480:35)
4/18/2018 6:31:25 PM    at Plugin.exports.hook_unrecognized_command (/usr/local/lib/node_modules/Haraka/plugins/auth/auth_base.js:35:52)
4/18/2018 6:31:25 PM    at Object.plugins.run_next_hook (/usr/local/lib/node_modules/Haraka/plugins.js:505:28)
4/18/2018 6:31:25 PM    at callback (/usr/local/lib/node_modules/Haraka/plugins.js:463:32)
4/18/2018 6:31:25 PM    at Plugin.exports.upgrade_connection (/usr/local/lib/node_modules/Haraka/plugins/tls.js:90:44)
4/18/2018 6:31:25 PM    at Object.plugins.run_next_hook (/usr/local/lib/node_modules/Haraka/plugins.js:505:28)
4/18/2018 6:31:25 PM    at callback (/usr/local/lib/node_modules/Haraka/plugins.js:463:32)
4/18/2018 6:31:25 PM    at Plugin.exports.hook_unrecognized_command (/etc/haraka/plugins/xclient.js:43:16)
4/18/2018 6:31:25 PM    at Object.plugins.run_next_hook (/usr/local/lib/node_modules/Haraka/plugins.js:505:28)
4/18/2018 6:31:25 PM    at Object.plugins.run_hooks (/usr/local/lib/node_modules/Haraka/plugins.js:422:13)
4/18/2018 6:31:25 PM    at Connection.process_line (/usr/local/lib/node_modules/Haraka/connection.js:342:25)
4/18/2018 6:31:25 PM    at Connection._process_data (/usr/local/lib/node_modules/Haraka/connection.js:464:22)
4/18/2018 6:31:25 PM    at Connection.respond (/usr/local/lib/node_modules/Haraka/connection.js:561:14)
4/18/2018 6:31:25 PM    at Connection.connect_respond (/usr/local/lib/node_modules/Haraka/connection.js:793:22)
4/18/2018 6:31:25 PM    at callback (/usr/local/lib/node_modules/Haraka/plugins.js:480:35)
4/18/2018 6:31:25 PM    at Plugin.exports.hook_connect (/etc/haraka/plugins/abusix_stats.js:19:12)
4/18/2018 6:31:25 PM    at Object.plugins.run_next_hook (/usr/local/lib/node_modules/Haraka/plugins.js:505:28)
4/18/2018 6:31:25 PM    at Object.plugins.run_hooks (/usr/local/lib/node_modules/Haraka/plugins.js:422:13)
4/18/2018 6:31:25 PM    at Connection.rdns_response (/usr/local/lib/node_modules/Haraka/connection.js:729:17)
4/18/2018 6:31:25 PM    at QueryReqWrap.dns.reverse [as callback] (/usr/local/lib/node_modules/Haraka/connection.js:708:26)
`````

My vote would be to just revert it as the old code did not have these issues.

**Comment by msimerson** [comment]
Maybe revert just the problematic change. Replacing the string concatenations isn't the problem. [This is](https://github.com/haraka/Haraka/blob/master/connection.js#L327):

```js
const [ , methodMatch, , remainingMatch] = /^([^ ]*)( +(.*))?$/.exec(this.current_line);
```

It presumes that  the regex will always match, which isn't a safe assumption.

**Comment by smfreegard** [comment]
> Maybe revert just the problematic change

Sorry; that was what I meant.

**Comment by msimerson** [comment]
Another option is to wrap it in a `try { } catch (ignore) {};` I keep forgetting that try/catch is no longer horrifically expensive.

**Comment by smfreegard** [comment]
I've done that already, feels nasty.   I'm just going to put the original code back instead, as that was sufficient.

**Comment by smfreegard** [comment]
(bearing in mind that is a 'hot' block of code too)
