### ISSUE TITLE
Plugin geoip failed

### ISSUE THREAD

**Issue by lnedry** [haraka/Haraka#2460]
### system info

Haraka | Haraka.js — Version: 2.8.16
 --- | :--- 
Node | v6.14.2
OS | Linux mx.bluestreak.net 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.0.2k-fips  26 Jan 2017

### Expected behavior
No crash

### Observed behavior

[CRIT] [E0501D5A-009E-408B-8368-6D159F18F798.1] [core] Plugin geoip failed: TypeError: Cannot read property 'iso_ode' of undefined
    at Plugin.exports.originating_headers (/usr/lib/node_modules/Haraka/node_modules/haraka-plugin-geoip/index.js:309:38)
    at Plugin.exports.add_headers (/usr/lib/node_modules/Haraka/node_modules/haraka-plugin-geoip/index.js:184:19)
    at Object.plugins.run_next_hook (/usr/lib/node_modules/Haraka/plugins.js:506:28)
    at callback (/usr/lib/node_modules/Haraka/plugins.js:462:32)
    at Plugin.exports.hook_data_post (/usr/lib/node_modules/Haraka/node_modules/haraka-plugin-p0f/index.js:248:16)
    at Object.plugins.run_next_hook (/usr/lib/node_modules/Haraka/plugins.js:506:28)
    at Object.plugins.run_hooks (/usr/lib/node_modules/Haraka/plugins.js:421:13)
    at MessageStream.end_callback (/usr/lib/node_modules/Haraka/connection.js:1695:17)
    at MessageStream._write (/usr/lib/node_modules/Haraka/messagestream.js:138:37)
    at ChunkEmitter.<anonymous> (/usr/lib/node_modules/Haraka/messagestream.js:64:18)

### Steps to reproduce
Fails when property 'iso_ode' is undefined

**Comment by msimerson** [comment]
Hi @lnedry , thanks for the report. Can you please publish this to the [haraka-plugin-geoip](https://github.com/haraka/haraka-plugin-geoip) repo instead?  Thanks.
