### ISSUE TITLE
outgoing tls (cluster mode): TypeError: Cannot read property 'redis' of undefined

### ISSUE THREAD

**Issue by sriccio** [haraka/Haraka#2471]
### system info
Haraka | Haraka.js — Version: 2.8.20 (pulled from git)
 --- | :--- 
Node | v10.6.0
OS | Linux out-mta01 4.16.0-0.bpo.2-amd64 #1 SMP Debian 4.16.16-2~bpo9+1 (2018-06-26) x86_64 GNU/Linux
openssl | OpenSSL 1.1.0f  25 May 2017

I'm using haraka for both outgoing and incoming smtp (relaying with smtp auth), daemonized and configured with nodes=cpus.
Seems there is some kind of race condition in the redis part of outgoing/tls.

### Expected behavior
Everything running smooth

### Observed behavior
Not always but most of the times an outgoing mail session ends, the worker crashes at trying to read tls plugin redis configuration, like if the redis object vanished before the plugin finished his work.

```
2018-07-14T20:38:46.895Z [NOTICE] [13616307-8613-4460-988A-64A303F80ACF.1] [core] message mid=<f5565af1d09e9334d0fdbae0ed7e3a3c@www.whatever.tld> size=6418 rcpts=1/0/0 delay=4.048 code=CONT msg=""
2018-07-14T20:38:46.895Z [NOTICE] [13616307-8613-4460-988A-64A303F80ACF.1] [core] queue code=CONT msg="Message Queued (13616307-8613-4460-988A-64A303F80ACF.1)"
2018-07-14T20:38:46.902Z [NOTICE] [13616307-8613-4460-988A-64A303F80ACF.1] [core] queue code=OK msg="Message Queued (13616307-8613-4460-988A-64A303F80ACF.1)"
2018-07-14T20:38:46.910Z [NOTICE] [13616307-8613-4460-988A-64A303F80ACF.1] [core] disconnect ip=94.103.96.220 rdns=web01.yesyes.com helo=web01.yesyes.com relay=Y early=N esmtp=Y tls=Y pipe=N errors=0 txns=1 rcpts=1/0/0 msgs=1/0/0 bytes=6418 lr="" time=4.938
2018-07-14T20:38:46.944Z [CRIT] [-] [core] TypeError: Cannot read property 'redis' of undefined
2018-07-14T20:38:46.944Z [CRIT] [-] [core]     at Object.exports.check_tls_nogo (/opt/haraka/outbound/tls.js:77:21)
2018-07-14T20:38:46.944Z [CRIT] [-] [core]     at process_ehlo_data (/opt/haraka/outbound/hmail.js:562:34)
2018-07-14T20:38:46.944Z [CRIT] [-] [core]     at pluggableStream.<anonymous> (/opt/haraka/outbound/hmail.js:787:21)
2018-07-14T20:38:46.945Z [CRIT] [-] [core]     at pluggableStream.emit (events.js:182:13)
2018-07-14T20:38:46.945Z [CRIT] [-] [core]     at pluggableStream.on_socket_data (/opt/haraka/line_socket.js:25:20)
2018-07-14T20:38:46.945Z [CRIT] [-] [core]     at pluggableStream.emit (events.js:182:13)
2018-07-14T20:38:46.945Z [CRIT] [-] [core]     at Socket.<anonymous> (/opt/haraka/tls_socket.js:59:18)
2018-07-14T20:38:46.945Z [CRIT] [-] [core]     at Socket.emit (events.js:182:13)
2018-07-14T20:38:46.945Z [CRIT] [-] [core]     at addChunk (_stream_readable.js:283:12)
2018-07-14T20:38:46.945Z [CRIT] [-] [core]     at readableAddChunk (_stream_readable.js:264:11)
2018-07-14T20:38:46.945Z [NOTICE] [-] [core] Shutting down
2018-07-14T20:38:46.949Z [NOTICE] [-] [core] worker 3 exited with error code: 1
2018-07-14T20:38:47.011Z [NOTICE] [-] [core] worker started worker=22 pid=23013
```

### Steps to reproduce
Use tls in outgoing smtp mode, with nodes=cpu and daemonized.

### Additional info
My tls.ini file
```
key=tls/privkey.pem
cert=tls/fullchain.pem
dhparam=tls/dhparams.pem

; ciphers: a list of permitted ciphers
; The default cipher list is provided by node.js and is considered secure at
; the time of that versions release. If you have problems with the default cipher
; list, try enabling this "kinda high but more compatible" setting.
ciphers=ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:DES-CBC3-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4

honorCipherOrder=false
rejectUnauthorized=false
requestCert=true
requestOCSP=false

[redis]
disable_for_failed_hosts=false

[no_tls_hosts]
127.0.0.1
; 192.168.1.1
; 172.16.0.0/16

[outbound]
; key=tls_key.pem
; cert=tls_cert.pem
; dhparam=dhparams.pem

; and other options from [main] section above
```

**Comment by baudehlo** [comment]
I'm trying to read the code and it's a bit bizarre because it's using
`plugin` and `this` like it's a plugin, but it's not. It's just exported
functions being called, so `this` is a weird concept.

The tls.js file needs re-implemented as a first-class class. I'll look into
it.

**Comment by msimerson** [comment]
It is weird and needs some cleanup. I think I spotted the flow control issue that caused .cfg to be undefined, and I also added checks for `cfg.redis` definedness. More should be done to clean this up but I think #2472 will fix the @sriccio issue.

**Comment by baudehlo** [comment]
Yeah I’m almost done with the cleanup. Just got to figure out that test failure.

**Comment by sriccio** [comment]
Hi, I've tested with tls.js from #2472. Well done, no more undefined redis errors ! Thanks !
