### ISSUE TITLE
Issuing a random INTERNALCMD on port 25 crashes the whole cluster

### ISSUE THREAD

**Issue by sriccio** [haraka/Haraka#2473]
### system info
Haraka | Haraka.js — Version: 2.8.20 (pulled from git)
 --- | :--- 
Node | v10.6.0
OS | Linux out-mta01 4.16.0-0.bpo.2-amd64 #1 SMP Debian 4.16.16-2~bpo9+1 (2018-06-26) x86_64 GNU/Linux
openssl | OpenSSL 1.1.0f  25 May 2017

### Expected behavior
Reply with something (command not found, missing key?) or nothing, but at least do not crash the whole instance (master process too) (cluster mode)

### Observed behavior
2018-07-15T22:50:21.427Z [ERROR] [-] [core] Invalid command: 89c68114f5edc7bb786b78a411ba0e8daa65697b347d95c660a8bfba826d2977
2018-07-15T22:50:21.427Z [CRIT] [-] [core] TypeError: Cannot read property 'apply' of undefined
2018-07-15T22:50:21.427Z [CRIT] [-] [core]     at Object.Server.receiveAsMaster (/opt/haraka/server.js:242:21)
2018-07-15T22:50:21.427Z [CRIT] [-] [core]     at EventEmitter.messageHandler (/opt/haraka/server.js:254:16)
2018-07-15T22:50:21.427Z [CRIT] [-] [core]     at EventEmitter.emit (events.js:182:13)
2018-07-15T22:50:21.427Z [CRIT] [-] [core]     at Worker.<anonymous> (internal/cluster/master.js:177:13)
2018-07-15T22:50:21.428Z [CRIT] [-] [core]     at Worker.emit (events.js:187:15)
2018-07-15T22:50:21.428Z [CRIT] [-] [core]     at ChildProcess.Worker.process.on (internal/cluster/worker.js:28:12)
2018-07-15T22:50:21.428Z [CRIT] [-] [core]     at ChildProcess.emit (events.js:182:13)
2018-07-15T22:50:21.428Z [CRIT] [-] [core]     at emit (internal/child_process.js:811:12)
2018-07-15T22:50:21.428Z [CRIT] [-] [core]     at process._tickCallback (internal/process/next_tick.js:63:19)

### Steps to reproduce
While trying to understand how to flush the queue using INTERNALCMD, i was able to instantanly crash the whole haraka daemon.

telnet localhost 25
Trying ::1...
Connected to localhost.
Escape character is '^]'.
220 some.fancy.prompt ESMTP Haraka ready
INTERNALCMD somekey help
250 Command sent for execution. Check Haraka logs for results.
Connection closed by foreign host.

**Comment by celesteking** [comment]
try #2428 maybe?

**Comment by sriccio** [comment]
Yes, okay I understand. I just thought it would be good to have some failsafe routine so that if a command is malformed or unknown, it doesn't crash the whole thing.

Hopefully there is the "localhost" check that prevent any external bozo to crash your Haraka service.

But what if you use Haraka on the same machine that has a webserver, hosting customers php (or whatever) scripts, that could connect to it from localhost ?

That's not our case but, just thinking out of the box :)

**Comment by sriccio** [comment]
Maybe just an "easy" way to avoid this. If i'm not wrong the syntax is:

`INTERNALCMD <secretkey> <command and stuff>` ?

In that cas could it be possible to filter out attemps by first verifying that the key is valid ? And politely reject if it doesn't match.

My tests shows that even with an invalid key the thing crashes.

```
# telnet localhost 25
Trying ::1...
Connected to localhost.
Escape character is '^]'.
220 out-crashme.somedomaine.com ESMTP Haraka ready
INTERNALCMD caca
250 Command sent for execution. Check Haraka logs for results.
Connection closed by foreign host.
```

```
2018-07-21T07:58:51.854Z [NOTICE] [71794746-D611-43E5-A5D4-53F18F9C6053] [core] connect ip=::1 port=57278 local_ip=:: local_port=25
2018-07-21T07:58:56.191Z [ERROR] [-] [core] Invalid command: caca
2018-07-21T07:58:56.192Z [CRIT] [-] [core] TypeError: Cannot read property 'apply' of undefined
2018-07-21T07:58:56.192Z [CRIT] [-] [core]     at Object.Server.receiveAsMaster (/opt/haraka/server.js:242:21)
2018-07-21T07:58:56.192Z [CRIT] [-] [core]     at EventEmitter.messageHandler (/opt/haraka/server.js:254:16)
2018-07-21T07:58:56.192Z [CRIT] [-] [core]     at EventEmitter.emit (events.js:182:13)
2018-07-21T07:58:56.193Z [CRIT] [-] [core]     at Worker.<anonymous> (internal/cluster/master.js:177:13)
2018-07-21T07:58:56.193Z [CRIT] [-] [core]     at Worker.emit (events.js:187:15)
2018-07-21T07:58:56.193Z [CRIT] [-] [core]     at ChildProcess.Worker.process.on (internal/cluster/worker.js:28:12)
2018-07-21T07:58:56.193Z [CRIT] [-] [core]     at ChildProcess.emit (events.js:182:13)
2018-07-21T07:58:56.193Z [CRIT] [-] [core]     at emit (internal/child_process.js:811:12)
2018-07-21T07:58:56.193Z [CRIT] [-] [core]     at process._tickCallback (internal/process/next_tick.js:63:19)
```
I'm not willing to bug you with this, just trying to find a way to cleanly handle this.

**Comment by sriccio** [comment]
hi @baudehlo, thanks a lot for the fix. It now doesn't crash anymore when issuing an invalid internalcmd.

```
2018-07-22T14:17:59.519Z [NOTICE] [B811C531-5716-4C6F-84E6-EE666C90381F] [core] connect ip=::1 port=54320 local_ip=:: local_port=25
2018-07-22T14:18:04.221Z [ERROR] [-] [core] Invalid command: testtest
2018-07-22T14:18:32.703Z [NOTICE] [B811C531-5716-4C6F-84E6-EE666C90381F] [core] disconnect ip=::1 rdns=ip6-localhost helo="" relay=N early=N esmtp=N tls=N pipe=N errors=5 txns=0 rcpts=0/0/0 msgs=0/0/0 bytes=0 lr="500 Unrecognized command" time=33.193
```

Great fix :)
