### ISSUE TITLE
Didn't find right amount of data in todo

### ISSUE THREAD

**Issue by thenitai** [haraka/Haraka#2504]
### system info

Please report your OS, Node version, and Haraka version by running this shell script on your Haraka server and replacing this section with the output.

Haraka | Haraka.js — Version: 2.8.21
 --- | :---
Node | v8.11.4
OS | Linux smtp2 4.4.0-134-generic #160-Ubuntu SMP Wed Aug 15 14:58:00 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

openssl | OpenSSL 1.0.2g  1 Mar 2016

### Expected behavior

Emails going out

### Observed behavior

2018-09-11T16:14:26.429Z [DEBUG] [AD071716-906A-4335-B0CD-1519CBD9A2A5] [core] [outbound] created
2018-09-11T16:14:26.430Z [CRIT] [-] [outbound] Didn't find right amount of data in todo!
2018-09-11T16:14:26.431Z [CRIT] [-] [core] Error: Unhandled "error" event. (Didn't find right amount of data in todo!)
2018-09-11T16:14:26.431Z [CRIT] [-] [core]     at HMailItem.emit (events.js:186:19)
2018-09-11T16:14:26.431Z [CRIT] [-] [core]     at _stream_bytes_from (/usr/lib/node_modules/Haraka/outbound/hmail.js:110:26)
2018-09-11T16:14:26.431Z [CRIT] [-] [core]     at ReadStream.stream.on (/usr/lib/node_modules/Haraka/outbound/hmail.js:149:13)
2018-09-11T16:14:26.431Z [CRIT] [-] [core]     at emitNone (events.js:111:20)
2018-09-11T16:14:26.431Z [CRIT] [-] [core]     at ReadStream.emit (events.js:208:7)
2018-09-11T16:14:26.431Z [CRIT] [-] [core]     at endReadableNT (_stream_readable.js:1064:12)
2018-09-11T16:14:26.431Z [CRIT] [-] [core]     at _combinedTickCallback (internal/process/next_tick.js:138:11)
2018-09-11T16:14:26.431Z [CRIT] [-] [core]     at process._tickCallback (internal/process/next_tick.js:180:9)
2018-09-11T16:14:26.432Z [NOTICE] [-] [core] Shutting down

All of the sudden seeing these error on our outgoing server. We didn't change anything lately. We run other additional servers and they do not show this behavior.

**Comment by baudehlo** [comment]
There should be a file in your queue directory called "error.<something>". Can you attach it to this ticket?

**Comment by thenitai** [comment]
Unfortunately, I don't have that error file anymore
