### ISSUE TITLE
LMTP delivery crashes haraka

### ISSUE THREAD

**Issue by pvagner** [haraka/Haraka#2509]
### system info

Haraka | Haraka.js — Version: 2.8.21
 --- | :--- 
Node | v10.11.0
OS | Linux vps.mydomain.tld 3.16.6-042stab127.46 #1 SMP Wed Mar 28 01:57:40 CEST 2018 x86_64 GNU/Linux
openssl | OpenSSL 1.1.1  11 Sep 2018

### Expected behavior

When sending out messages via lmtp to dovecot I started getting errors like this.
I am not able to figure out what might be affecting this. I have tried downgrading node and dovecot to previously working versions and I can't make it work.
Messages are delivered via lmtp however haraka crashes like this.
```

[DEBUG] [CA4E3D5B-E4FE-44A2-9643-5893B914DE33.1.1] [outbound] Sending mail: 1537885957544_1537885957544_0_21768_GGPZLK_1_vps.mydomain.tld
[DEBUG] [CA4E3D5B-E4FE-44A2-9643-5893B914DE33.1.1] [outbound] running get_mx hooks
[DEBUG] [CA4E3D5B-E4FE-44A2-9643-5893B914DE33.1.1] [outbound] running get_mx hook in queue/lmtp plugin
[NOTICE] [CA4E3D5B-E4FE-44A2-9643-5893B914DE33.1.1] [queue/lmtp] {"main":{"path":"/run/dovecot/lmtp"}}
[NOTICE] [CA4E3D5B-E4FE-44A2-9643-5893B914DE33.1.1] [queue/lmtp] {"using_lmtp":true,"priority":0,"exchange":"127.0.0.1","path":"/run/dovecot/lmtp"}
[INFO] [CA4E3D5B-E4FE-44A2-9643-5893B914DE33.1.1] [outbound]  hook=get_mx plugin=queue/lmtp function=hook_get_mx params=exampledomain.com retval=OK msg="[object Object]"
[DEBUG] [CA4E3D5B-E4FE-44A2-9643-5893B914DE33.1.1] [outbound] Got an MX from Plugin: exampledomain.com => 0 [object Object]
[INFO] [CA4E3D5B-E4FE-44A2-9643-5893B914DE33.1.1] [outbound] Attempting to deliver to: /run/dovecot/lmtp:25 using LMTP (0) (0)
[INFO] [-] [core] [outbound] [outbound::25:/run/dovecot/lmtp:undefined:0] dispense() clients=1 available=0
[DEBUG] [-] [core] [outbound] [outbound::25:/run/dovecot/lmtp:undefined:0] createResource() - creating obj - count=1 min=0 max=10
[DEBUG] [8EA6BF2D-E14A-4066-9901-095F6EA4E14A] [core] [outbound] created
[INFO] [-] [core] [outbound] acquired socket 8EA6BF2D-E14A-4066-9901-095F6EA4E14A for outbound::25:/run/dovecot/lmtp:undefined:0
[DEBUG] [CA4E3D5B-E4FE-44A2-9643-5893B914DE33.1.1] [outbound] Trying TLS for domain: exampledomain.com, host: /run/dovecot/lmtp
[DEBUG] [-] [core] client TLS upgrade in progress, awaiting secured.
[DEBUG] [-] [core] client TLS secured.
[INFO] [CA4E3D5B-E4FE-44A2-9643-5893B914DE33.1.1] [outbound] secured verified=false cipher=TLS_AES_256_GCM_SHA384 version=TLSv1/SSLv3 error=ERR_TLS_CERT_ALTNAME_INVALID cn=mail.mydomain.tld organization="" issuer="Let's Encrypt" expires="Dec 20 18:06:46 2018 GMT" fingerprint=6D:CC:77:3D:63:51:A8:4B:AE:0B:8A:28:1B:69:6E:B5:E1:C2:DB:73
[DEBUG] [-] [core] client TLS secured.
[INFO] [CA4E3D5B-E4FE-44A2-9643-5893B914DE33.1.1] [outbound] secured verified=false cipher=TLS_AES_256_GCM_SHA384 version=TLSv1/SSLv3 error=ERR_TLS_CERT_ALTNAME_INVALID cn=mail.mydomain.tld organization="" issuer="Let's Encrypt" expires="Dec 20 18:06:46 2018 GMT" fingerprint=6D:CC:77:3D:63:51:A8:4B:AE:0B:8A:28:1B:69:6E:B5:E1:C2:DB:73
[DEBUG] [-] [core] client TLS secured.
[INFO] [CA4E3D5B-E4FE-44A2-9643-5893B914DE33.1.1] [outbound] secured verified=false cipher=TLS_AES_256_GCM_SHA384 version=TLSv1/SSLv3 error=ERR_TLS_CERT_ALTNAME_INVALID cn=mail.mydomain.tld organization="" issuer="Let's Encrypt" expires="Dec 20 18:06:46 2018 GMT" fingerprint=6D:CC:77:3D:63:51:A8:4B:AE:0B:8A:28:1B:69:6E:B5:E1:C2:DB:73
[NOTICE] [CA4E3D5B-E4FE-44A2-9643-5893B914DE33.1.1] [outbound]  delivered file=1537885957544_1537885957544_0_21768_GGPZLK_1_vps.mydomain.tld domain=exampledomain.com host=127.0.0.1 ip=/run/dovecot/lmtp port=25 mode=LMTP tls=Y auth=N response=OK delay=0.167 fails=0 rcpts=1/0/0
[DEBUG] [CA4E3D5B-E4FE-44A2-9643-5893B914DE33.1.1] [ou		tbound] running delivered hooks
[DEBUG] [-] [core] Temp fail for: Upstream error: 354OK
[DEBUG] [CA4E3D5B-E4FE-44A2-9643-5893B914DE33.1.1] [outbound] running deferred hooks
[INFO] [CA4E3D5B-E4FE-44A2-9643-5893B914DE33.1.1] [outbound] Temp failing 1537885957544_1537885957544_0_21768_GGPZLK_1_vps.mydomain.tld for 64 seconds: Upstream error: 354OK
[INFO] [CA4E3D5B-E4FE-44A2-9643-5893B914DE33.1.1] [outbound] bouncing mail: Error re-queueing email: Error: ENOENT: no such file or directory, rename '/srv/haraka/inbound/queue/1537885957544_1537885957544_0_21768_GGPZLK_1_vps.mydomain.tld' -> '/srv/haraka/inbound/queue/1537885957544_1537886021711_1_21768_GGPZLK_2_vps.mydomain.tld'
[DEBUG] [CA4E3D5B-E4FE-44A2-9643-5893B914DE33.1.1] [outbound] running bounce hooks
[NOTICE] [CA4E3D5B-E4FE-44A2-9643-5893B914DE33.1.1] [outbound] Double bounce: Error populating bounce message: Error: ENOENT: no such file or directory, open '/srv/haraka/inbound/queue/1537885957544_1537885957544_0_21768_GGPZLK_1_vps.mydomain.tld'
[CRIT] [-] [core] Error: Callback was already called.
[CRIT] [-] [core]     at /usr/lib/node_modules/Haraka/node_modules/async/dist/async.js:966:32
[CRIT] [-] [core]     at HMailItem.hmail.next_cb (/usr/lib/node_modules/Haraka/outbound/queue.js:41:9)
[CRIT] [-] [core]     at HMailItem.double_bounce (/usr/lib/node_modules/Haraka/outbound/hmail.js:1254:14)
[CRIT] [-] [core]     at /usr/lib/node_modules/Haraka/outbound/hmail.js:1238:29
[CRIT] [-] [core]     at ReadStream.<anonymous> (/usr/lib/node_modules/Haraka/outbound/hmail.js:941:17)
[CRIT] [-] [core]     at ReadStream.emit (events.js:182:13)
[CRIT] [-] [core]     at lazyFs.open (internal/fs/streams.js:115:12)
[CRIT] [-] [core]     at FSReqWrap.oncomplete (fs.js:141:20)
```
[NOTICE] [-] [core] Shutting down
```

### Observed behavior

It's happening to me since a few days ago however I have already tried reverting possible upgrades to restore the previous behaviour where haraka delivers messages via LMTP and don't crashes.

### Steps to reproduce
* Configure dovecot to accept mails via lmtp
* Configure haraka to deliver messages to dovecot.
* Send a message to haraka.

**Comment by AuspeXeu** [comment]
Maybe you can provide your configuration?

**Comment by baudehlo** [comment]
I don't think we need configuration - I understand the problem - LMTP does
things out of order so it's not setup to cope with rejected mail. The stack
trace is enough to fix it, just ENOTIME.

**Comment by baudehlo** [comment]
I haven't accounted for anything except that there's a bug and you've given
enough logs to fix it if I find time to dig into it.

I'm also using Haraka with LMTP so if it breaks on a Haraka upgrade I have
a vested interest in fixing it. I'm just super busy right now.

**Comment by msimerson** [comment]
No.

**Comment by analogic** [comment]
@baudehlo do you know how to reproduce this issue?

**Comment by baudehlo** [comment]
You get the LMTP server to issue a temp fail response to a command. (how
you achieve that is a mystery, but that's the issue).

**Comment by msimerson** [comment]
I haven't tested, but I'd start by setting a quota for a mailbox below its current contents. Dovecot will then issue a temp or perm fail.

**Comment by analogic** [comment]
I don't think it is the case. I have tested same situation at https://github.com/haraka/Haraka/pull/2470.  Thing which puzzles me is "Temp fail for: Upstream error: 354OK" and mainly "delivered..." log vs "Temp failing..." or doubled or tripled log lines. It seems to me like some concurrency problem

**Comment by analogic** [comment]
@pvagner is it possible that the bug was triggered by malformed email?

**Comment by baudehlo** [comment]
354 is the response LMTP should get from the DATA command. So I wonder if
it somehow got mashed together, so instead of "354 OK" we saw "354OK".
Weird.

**Comment by analogic** [comment]
Missing space is normal, see https://github.com/haraka/Haraka/blob/de29e32e09862a2c4e81e90ad9067c555f57a92f/outbound/hmail.js#L699
As we now know where it ends, we also know that the last sent command was not DATA

**Comment by baudehlo** [comment]
In that case I'm utterly confused :)

**Comment by analogic** [comment]
Is there any possibility that this event is fired three times?

https://github.com/haraka/Haraka/blob/3d1ccdb2cf31c53936224ef66c09caba9872b06e/tls_socket.js#L710

My wild guess is that disabling TLS on LMTP will solve the issue - TLS on local socket is not even necessary and who knows if node has tls on unix socket properly implemented

**Comment by baudehlo** [comment]
How about a PR to change those `.on()`s to `.once()`s?
