### ISSUE TITLE
Dockerfile: Issue with haraka.sh

### ISSUE THREAD

**Issue by surmer** [haraka/Haraka#2550]
### system info

I'm running the Docker-specified node 5.x, and Haraka 2.8.23.

### Expected behavior
When I run `docker build .` in the main Haraka directory, I was expecting Docker to properly build the container.

### Observed behavior
Instead, I received this error: 
```
/usr/lib/node_modules/Haraka/bin/haraka:93
    let plist = dir + "\n";
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3
```

I believe it's related to the old version of node that Dockerfile specifies. I was at least able to build it by changing the curl command to pull node version 10.x: `RUN curl -sL https://deb.nodesource.com/setup_10.x | setuser root bash -` and by adding the `--unsafe` flag to the `npm install -g Haraka command` (necessary otherwise node-gyp will refuse to install).

### Steps to reproduce
`docker build .`

**Comment by msimerson** [comment]
Maybe we should move the Dockerfile into the `contrib` directory to make it obvious that "we," the core members of the Haraka project don't *maintain* support for it.

A PR that updates the version of node in the Dockerfile to 8 or 10 is welcome.

**Comment by surmer** [comment]
Happy to do a PR for it. Should be a relatively easy fix. Contrib makes a
lot of sense, although Dockerfiles are best stored in the root directory of
the repo. Maybe adding a comment to the Dockerfile to make it clear that
it's user-contributed and not officially supported? Happy to go either way
though.

Le sam. 1 déc. 2018 à 18:14, Matt Simerson <notifications@github.com> a
écrit :
