### ISSUE TITLE
haraka_require Error: Cannot find module

### ISSUE THREAD

**Issue by ztipnis** [haraka/Haraka#2670]
### system info

Haraka | Haraka.js — Version: 2.8.24
 --- | :---
Node | v12.4.0
OS | Darwin `hostname` 18.7.0 Darwin Kernel Version 18.7.0: Sun Jun  2 21:24:32 PDT 2019; root:xnu-4903.270.37~8/RELEASE_X86_64 x86_64
openssl | LibreSSL 2.6.5

### Expected behavior

Address Object Module imported

### Observed behavior
```
Plugin lists failed: Error: Cannot find module './address'
Require stack:
- /usr/local/lib/node_modules/Haraka/plugins.js
- /usr/local/lib/node_modules/Haraka/logger.js
- /usr/local/lib/node_modules/Haraka/haraka.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Plugin.haraka_require (/usr/local/lib/node_modules/Haraka/plugins.js:34:16)
    at Plugin.core_require (/usr/local/lib/node_modules/Haraka/plugins.js:38:21)
    at Plugin.exports.load_recipients (/Users/zatipnis/haraka-plugin-lists/index.js:85:27)
    at Object.plugins.run_next_hook (/usr/local/lib/node_modules/Haraka/plugins.js:508:28)
    at Object.plugins.run_hooks (/usr/local/lib/node_modules/Haraka/plugins.js:422:13)
    at Connection.data_post_respond (/usr/local/lib/node_modules/Haraka/connection.js:1712:29)
```
### Steps to reproduce

```
exports.load_recipients = function (next, connection){
    const plugin = this;
    const AddObj = plugin.core_require('address');
    .
    .
    .
}
```

**Comment by ztipnis** [comment]
Address is not (no longer?) a haraka module it seems,
looks like it was moved to https://github.com/haraka/node-address-rfc2822
