### ISSUE TITLE
npm i -g Haraka (2.8.24) fails 

### ISSUE THREAD

**Issue by sunandosamaddar** [haraka/Haraka#2690]
- **OS** Deepin 15.11
- **Node**@v12.8.0
- **openssl**@1.1.1c

### Steps to reproduce
`sudo npm i -g Haraka`

### Observed behavior
```
/usr/bin/haraka -> /usr/lib/node_modules/Haraka/bin/haraka
/usr/bin/spf -> /usr/lib/node_modules/Haraka/bin/spf
/usr/bin/dkimverify -> /usr/lib/node_modules/Haraka/bin/dkimverify
/usr/bin/haraka_grep -> /usr/lib/node_modules/Haraka/bin/haraka_grep

> dtrace-provider@0.8.8 install /usr/lib/node_modules/Haraka/node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js

gyp WARN EACCES user "nobody" does not have permission to access the dev dir "/root/.cache/node-gyp/12.8.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/Haraka/node_modules/dtrace-provider/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/Haraka/node_modules/dtrace-provider/.node-gyp'
gyp ERR! System Linux 4.15.0-30deepin-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/Haraka/node_modules/dtrace-provider
gyp ERR! node -v v12.8.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 

> modern-syslog@1.2.0 install /usr/lib/node_modules/Haraka/node_modules/modern-syslog
> node-gyp rebuild

gyp WARN EACCES user "nobody" does not have permission to access the dev dir "/root/.cache/node-gyp/12.8.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/Haraka/node_modules/modern-syslog/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/Haraka/node_modules/modern-syslog/.node-gyp'
gyp ERR! System Linux 4.15.0-30deepin-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/Haraka/node_modules/modern-syslog
gyp ERR! node -v v12.8.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 

> sqlite3@4.1.0 install /usr/lib/node_modules/Haraka/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for sqlite3@4.1.0 and node@12.8.0 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/usr/lib/node_modules/Haraka/node_modules/sqlite3/lib/binding' 
gyp WARN EACCES user "nobody" does not have permission to access the dev dir "/root/.cache/node-gyp/12.8.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/Haraka/node_modules/sqlite3/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/Haraka/node_modules/sqlite3/.node-gyp'
gyp ERR! System Linux 4.15.0-30deepin-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/lib/node_modules/Haraka/node_modules/sqlite3/lib/binding/node-v72-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/usr/lib/node_modules/Haraka/node_modules/sqlite3/lib/binding/node-v72-linux-x64" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /usr/lib/node_modules/Haraka/node_modules/sqlite3
gyp ERR! node -v v12.8.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/lib/node_modules/Haraka/node_modules/sqlite3/lib/binding/node-v72-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/usr/lib/node_modules/Haraka/node_modules/sqlite3/lib/binding/node-v72-linux-x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/Haraka/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Linux 4.15.0-30deepin-generic
node-pre-gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/Haraka/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/lib/node_modules/Haraka/node_modules/sqlite3
node-pre-gyp ERR! node -v v12.8.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/lib/node_modules/Haraka/node_modules/sqlite3/lib/binding/node-v72-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/usr/lib/node_modules/Haraka/node_modules/sqlite3/lib/binding/node-v72-linux-x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)

> iconv@2.3.4 install /usr/lib/node_modules/Haraka/node_modules/iconv
> node-gyp rebuild

gyp WARN EACCES user "nobody" does not have permission to access the dev dir "/root/.cache/node-gyp/12.8.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/Haraka/node_modules/iconv/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/Haraka/node_modules/iconv/.node-gyp'
gyp ERR! System Linux 4.15.0-30deepin-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/Haraka/node_modules/iconv
gyp ERR! node -v v12.8.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: modern-syslog@1.2.0 (node_modules/Haraka/node_modules/modern-syslog):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: modern-syslog@1.2.0 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sqlite3@4.1.0 (node_modules/Haraka/node_modules/sqlite3):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sqlite3@4.1.0 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iconv@2.3.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iconv@2.3.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-08-29T06_22_17_682Z-debug.log
```

**Comment by msimerson** [comment]
Did you try `npm -g config set user root` from the README?

**Comment by sunandosamaddar** [comment]
When `sudo npm i -g Haraka` after above cmd.

```
/usr/bin/haraka -> /usr/lib/node_modules/Haraka/bin/haraka
/usr/bin/spf -> /usr/lib/node_modules/Haraka/bin/spf
/usr/bin/dkimverify -> /usr/lib/node_modules/Haraka/bin/dkimverify
/usr/bin/haraka_grep -> /usr/lib/node_modules/Haraka/bin/haraka_grep

> dtrace-provider@0.8.8 install /usr/lib/node_modules/Haraka/node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js

make: Entering directory '/usr/lib/node_modules/Haraka/node_modules/dtrace-provider/build'
  TOUCH Release/obj.target/DTraceProviderStub.stamp
make: Leaving directory '/usr/lib/node_modules/Haraka/node_modules/dtrace-provider/build'

> modern-syslog@1.2.0 install /usr/lib/node_modules/Haraka/node_modules/modern-syslog
> node-gyp rebuild

make: Entering directory '/usr/lib/node_modules/Haraka/node_modules/modern-syslog/build'
  CXX(target) Release/obj.target/core/core.o
make: g++: Command not found
core.target.mk:111: recipe for target 'Release/obj.target/core/core.o' failed
make: *** [Release/obj.target/core/core.o] Error 127
make: Leaving directory '/usr/lib/node_modules/Haraka/node_modules/modern-syslog/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.15.0-30deepin-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/Haraka/node_modules/modern-syslog
gyp ERR! node -v v12.8.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 

> sqlite3@4.1.0 install /usr/lib/node_modules/Haraka/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
[sqlite3] Success: "/usr/lib/node_modules/Haraka/node_modules/sqlite3/lib/binding/node-v72-linux-x64/node_sqlite3.node" is installed via remote

> iconv@2.3.4 install /usr/lib/node_modules/Haraka/node_modules/iconv
> node-gyp rebuild

make: Entering directory '/usr/lib/node_modules/Haraka/node_modules/iconv/build'
  CXX(target) Release/obj.target/iconv/src/binding.o
make: g++: Command not found
iconv.target.mk:113: recipe for target 'Release/obj.target/iconv/src/binding.o' failed
make: *** [Release/obj.target/iconv/src/binding.o] Error 127
make: Leaving directory '/usr/lib/node_modules/Haraka/node_modules/iconv/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.15.0-30deepin-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/Haraka/node_modules/iconv
gyp ERR! node -v v12.8.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: modern-syslog@1.2.0 (node_modules/Haraka/node_modules/modern-syslog):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: modern-syslog@1.2.0 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iconv@2.3.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iconv@2.3.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-08-29T09_23_54_293Z-debug.log
```

**Comment by baudehlo** [comment]
sudo apt install build-essential

**Comment by sunandosamaddar** [comment]
Thanks a lot!!

**Comment by apmcodes** [comment]
> Did you try `npm -g config set user root` from the README?

This worked on a new Ubuntu setup. Thank you very much!

**Comment by sunandosamaddar** [comment]
That line, and then the next one worked great. I was little worried inside
Deepin to do build-essentials install.

**Comment by sunandosamaddar** [comment]
While reading the issue lists I came across references about
a Windows-based package, but was not sure whether it was called
build-essentials. Looking forward to using Haraka now!!
