### ISSUE TITLE
Use multiple certificates on Windows

### ISSUE THREAD

**Issue by Taxman972** [haraka/Haraka#2777]
### system info

I know Windows isn't **officially** supported but since Haraka works with 1 pair key/cert I think it should works with more pairs.

**System :** Windows Server 2012/2019
**Haraka version :** 2.8.25

### Expected behavior
This code in `tls.ini` should works

```
key[]=C:/Haraka-certificates/domain.fr.key.pem
cert[]=C:/Haraka-certificates/domain.fr-full.pem
key[]=C:/Haraka-certificates/another-domain.fr.key.pem
cert[]=C:/Haraka-certificates/another-domain.fr-full.pem
```

### Observed behavior
Only 1 pair can be active at the time

```
key[]=C:/Haraka-certificates/domain.fr.key.pem
cert[]=C:/Haraka-certificates/domain.fr-full.pem
;key[]=C:/Haraka-certificates/another-domain.fr.key.pem
;cert[]=C:/Haraka-certificates/another-domain.fr-full.pem
```
or 

```
;key[]=C:/Haraka-certificates/domain.fr.key.pem
;cert[]=C:/Haraka-certificates/domain.fr-full.pem
key[]=C:/Haraka-certificates/another-domain.fr.key.pem
cert[]=C:/Haraka-certificates/another-domain.fr-full.pem
```
If both are uncommented this error show in the log

```
[INFO] [-] [core] loading tls.ini
[CRIT] [-] [core] Error: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch
[CRIT] [-] [core]     at Object.createSecureContext (_tls_common.js:152:19)
[CRIT] [-] [core]     at tlss.ensureDhparams (C:\Haraka-smtp-server\tls_socket.js:395:34)
[CRIT] [-] [core]     at Object.exports.ensureDhparams.done [as ensureDhparams] (C:\Haraka-smtp-server\tls_socket.js:528:16)
[CRIT] [-] [core]     at Object.exports.load_default_opts (C:\Haraka-smtp-server\tls_socket.js:394:14)
[CRIT] [-] [core]     at Object.exports.load_tls_ini (C:\Haraka-smtp-server\tls_socket.js:269:14)
[CRIT] [-] [core]     at Plugin.exports.register (C:\Haraka-smtp-server\plugins\tls.js:13:16)
[CRIT] [-] [core]     at Object.plugins._register_plugin.plugin [as _register_plugin] (C:\Haraka-smtp-server\plugins.js:404:12)
[CRIT] [-] [core]     at Object.plugins.load_plugin.name [as load_plugin] (C:\Haraka-smtp-server\plugins.js:378:17)
[CRIT] [-] [core]     at plugin_list.forEach.plugin (C:\Haraka-smtp-server\plugins.js:327:21)
[CRIT] [-] [core]     at Array.forEach (<anonymous>)
[NOTICE] [-] [core] Shutting down
```

**Comment by msimerson** [comment]
Please [read the TLS docs](https://github.com/haraka/Haraka/blob/master/docs/plugins/tls.md#certificate-directory)

**Comment by Taxman972** [comment]
Hi @msimerson ,
When I use the [TLS directory](https://github.com/haraka/Haraka/blob/master/docs/plugins/tls.md#certificate-directory) config what should I write in `tls.ini` for the cert and key since all files in the folder are already loaded ?

**Comment by msimerson** [comment]
The "default" TLS certificate (it can be a duplicate in the `tls` dir.) If the remote doesn't offer TLS SNI, then that certificate is the one presented.
