### ISSUE TITLE
How to Daemonize Haraka

### ISSUE THREAD

**Issue by Abdeljalil0Cyclo** [haraka/Haraka#2799]
### system info
CentOS Linux release 8.1.1911 (Core), Node version : v12.16.3, and Haraka version  version 2.8.25
### Expected behavior
starting up without errors
### Observed behavior
[CRIT] [-] [core] Error: write EPIPE
[CRIT] [-] [core]     at process.target._send (internal/child_process.js:806:20)
[CRIT] [-] [core]     at process.target.send (internal/child_process.js:677:19)
[CRIT] [-] [core]     at sendHelper (internal/cluster/utils.js:26:15)
[CRIT] [-] [core]     at send (internal/cluster/child.js:193:10)
[CRIT] [-] [core]     at EventEmitter.cluster._setupWorker (internal/cluster/child.js:46:3)
[CRIT] [-] [core]     at initializeClusterIPC (internal/bootstrap/pre_execution.js:333:13)
[CRIT] [-] [core]     at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:59:3)
[CRIT] [-] [core]     at internal/main/run_main_module.js:7:1
[NOTICE] [-] [core] Shutting down
### Steps to reproduce
i initiated haraka , when starting i get that error when **Daemonized** is true can any one help please thanks

**Comment by Abdeljalil0Cyclo** [comment]
fixed this by adding file haraka.service with the content below which i found here
https://github.com/haraka/Haraka/blob/362c36de084202671b6f4506b7e2eacc25345c4c/contrib/haraka.service


```
#
# systemd service file for Haraka
#
# Ensure that `daemonize` in `smtp.ini` is set to `false` (which is the default value).
#
# Put this file in /etc/systemd/system,  modify the paths to suit, then run:
# sudo systemctl enable haraka
# sudo systemctl start haraka
#

[Unit]
Description=Haraka MTA
After=syslog.target network.target remote-fs.target nss-lookup.target

[Service]
Type=simple
PIDFile=/var/run/haraka.pid
ExecStart=/usr/bin/haraka -c /path/to/your/config
KillMode=process
PrivateTmp=true

[Install]
WantedBy=multi-user.target
```
