### ISSUE TITLE
running tests separately

### ISSUE THREAD

**Issue by celesteking** [haraka/Haraka#2801]
Can't understand why I can't run this test alone:

```
$ npm run test -- tests/outbound_bounce_rfc3464.js 

> Haraka@2.8.25 test /code/nodejs/node_modules/Haraka
> node run_tests "tests/outbound_bounce_rfc3464.js"

Running tests:  [ 'tests/outbound_bounce_rfc3464.js' ]
loaded TLD files: 1=1528 2=8564 3=2448
loaded 8787 Public Suffixes

outbound_bounce_rfc3464.js

/code/nodejs/node_modules/Haraka/outbound/hmail.js:929
        const header = new Header();
                       ^
TypeError: Header is not a constructor
    at HMailItem.populate_bounce_message (/code/nodejs/node_modules/Haraka/outbound/hmail.js:929:24)
    at HMailItem.bounce_respond (/code/nodejs/node_modules/Haraka/outbound/hmail.js:1252:14)
    at callback (/code/nodejs/node_modules/Haraka/plugins.js:510:35)
    at Object.plugins.run_next_hook (/code/nodejs/node_modules/Haraka/plugins.js:514:45)
    at Object.plugins.run_hooks (/code/nodejs/node_modules/Haraka/plugins.js:449:13)
    at HMailItem._bounce (/code/nodejs/node_modules/Haraka/outbound/hmail.js:1233:17)
    at HMailItem.bounce (/code/nodejs/node_modules/Haraka/outbound/hmail.js:1222:14)
    at Socket.<anonymous> (/code/nodejs/node_modules/Haraka/outbound/hmail.js:794:33)
    at Socket.emit (events.js:210:5)
    at Socket.EventEmitter.emit (domain.js:475:20)

FAILURES: Undone tests (or their setups/teardowns): 
- bounce_3464 - test MAIL FROM responded with 500 5.0.0 triggers send_email() containing bounce msg with codes and message

```

**Comment by celesteking** [comment]
Compare:
```
$ npm run test -- tests/outbound_bounce_net_errors.js 

> Haraka@2.8.25 test /code/nodejs/node_modules/Haraka
> node run_tests "tests/outbound_bounce_net_errors.js"

Running tests:  [ 'tests/outbound_bounce_net_errors.js' ]
loaded TLD files: 1=1528 2=8564 3=2448
loaded 8787 Public Suffixes

outbound_bounce_net_errors.js
✔ bounce_3464 - test get-mx-deny triggers bounce(...)
✔ bounce_3464 - test get-mx-denysoft triggers temp_fail(...)
✔ bounce_3464 - test found_mx({code:dns.NXDOMAIN}) triggers bounce(...)
✔ bounce_3464 - test found_mx({code:'NOMX'}) triggers bounce(...)
✔ bounce_3464 - test found_mx({code:'SOME-OTHER-ERR'}) triggers temp_fail(...)
✔ bounce_3464 - test found_mx(null, [{priority:0,exchange:''}]) triggers bounce(...)
✔ bounce_3464 - test try_deliver while hmail.mxlist=[] triggers bounce(...)

OK: 14 assertions (147ms)
```

**Comment by msimerson** [comment]
Because that's the way it is. I tried to decouple them once or twice over the years and ran out of interest before figuring out exactly why.
