### ISSUE TITLE
Regression in plugin name convention

### ISSUE THREAD

**Issue by AuspeXeu** [haraka/Haraka#2870]
### system info

Haraka.js — Version: 2.8.26
 --- | :---
Node | v14.15.0
OS | Linux
openssl | OpenSSL 1.1.1d  10 Sep 2019

### Expected behavior
Correctly load plugins and start up.

### Observed behavior
Crashes with
```
2020-12-04T08:51:33.078Z [CRIT] [-] [core] TypeError: Cannot read property 'timeout' of undefined
2020-12-04T08:51:33.078Z [CRIT] [-] [core]     at Object.plugins.run_next_hook (/mnt/c/Users/chris/repos/haraka-ep-outbound/node_modules/Haraka/plugins.js:522:35)
2020-12-04T08:51:33.079Z [CRIT] [-] [core]     at Object.plugins.run_hooks (/mnt/c/Users/chris/repos/haraka-ep-outbound/node_modules/Haraka/plugins.js:451:13)
2020-12-04T08:51:33.079Z [CRIT] [-] [core]     at Object.Server.createServer (/mnt/c/Users/chris/repos/haraka-ep-outbound/node_modules/Haraka/server.js:328:20)
2020-12-04T08:51:33.080Z [CRIT] [-] [core]     at Object.<anonymous> (/mnt/c/Users/chris/repos/haraka-ep-outbound/node_modules/Haraka/haraka.js:83:8)
2020-12-04T08:51:33.080Z [CRIT] [-] [core]     at Module._compile (internal/modules/cjs/loader.js:1063:30)
2020-12-04T08:51:33.081Z [CRIT] [-] [core]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
2020-12-04T08:51:33.081Z [CRIT] [-] [core]     at Module.load (internal/modules/cjs/loader.js:928:32)
2020-12-04T08:51:33.081Z [CRIT] [-] [core]     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
2020-12-04T08:51:33.082Z [CRIT] [-] [core]     at Module.require (internal/modules/cjs/loader.js:952:19)
2020-12-04T08:51:33.082Z [CRIT] [-] [core]     at require (internal/modules/cjs/helpers.js:88:18)
2020-12-04T08:51:33.084Z [NOTICE] [-] [core] Shutting down
```

### Steps to reproduce
Configure plugins like so
```
helo.checks
tls
haraka-plugin-auth-imap
haraka-plugin-access-auth
clamd
haraka-plugin-known-senders
haraka-plugin-recipient-routes
data.headers
```
and run Haraka like so
`yarn run haraka -c .`

**Comment by msimerson** [comment]
> Configure plugins like so

As a workaround, removing the `haraka-plugin` prefix from each plugin name should work.
