### ISSUE TITLE
crash in outbound

### ISSUE THREAD

**Issue by celesteking** [haraka/Haraka#2944]
Basically, crashes on bounce tempfail. Can't get what's wrong.
This has lines a bit off by 3 or so.

```
 [NOTICE] [46095497-C02F-40F5-81DF-8BAB88780C2F.1.1] [outbound] [FAEFC4FA-E8EF-4EC9-B8A4-0B5C7A413587] recipient domain <bell.net> rejected: 521 Service not available
 [ERROR] [46095497-C02F-40F5-81DF-8BAB88780C2F.1.1] [outbound] [FAEFC4FA-E8EF-4EC9-B8A4-0B5C7A413587] Ongoing connection failed to 184.150.200.82:25 : Error: write ECONNRESET
 [NOTICE] [-] [OutboundTLS] TLS connection failed. Marking 184.150.200.82 as non-TLS for 604800 seconds
 [INFO] [46095497-C02F-40F5-81DF-8BAB88780C2F.1.1] [outbound] [FAEFC4FA-E8EF-4EC9-B8A4-0B5C7A413587] bouncing mail: 521 Service not available
 [CRIT] [46095497-C02F-40F5-81DF-8BAB88780C2F.1.1] [outbound] [FAEFC4FA-E8EF-4EC9-B8A4-0B5C7A413587] Socket write failed unexpectedly: Error: write ECONNRESET
 [INFO] [-] [core] [outbound] Sending email via params
 [INFO] [-] [core] [outbound] Created transaction: 460ACB0C-4855-49F9-B76B-F70F8D72FC7D
 [INFO] [-] [core] [outbound] Processing delivery for domain: xxx.com
 [INFO] [46095497-C02F-40F5-81DF-8BAB88780C2F.1.1] [outbound] [FAEFC4FA-E8EF-4EC9-B8A4-0B5C7A413587] Temp failing 1618604144331_1618604144331_0_4295_Gfg8rO_683_xx for 64 seconds: Tried 
all MXs
 [CRIT] [-] [core] Error: Callback was already called.
 [CRIT] [-] [core]     at /mnt/haraka/Haraka/node_modules/async/dist/async.js:318:36
 [CRIT] [-] [core]     at HMailItem.hmail.next_cb (/mnt/haraka/Haraka/outbound/queue.js:41:9)
 [CRIT] [-] [core]     at HMailItem.discard (/mnt/haraka/Haraka/outbound/hmail.js:1355:18)
 [CRIT] [-] [core]     at outbound.send_email.origin (/mnt/haraka/Haraka/outbound/hmail.js:1313:22)
 [CRIT] [-] [core]     at /mnt/haraka/Haraka/outbound/index.js:287:17
 [CRIT] [-] [core]     at wrapper (/mnt/haraka/Haraka/node_modules/async/dist/async.js:268:20)
 [CRIT] [-] [core]     at replenish (/mnt/haraka/Haraka/node_modules/async/dist/async.js:435:29)
 [CRIT] [-] [core]     at iterateeCallback (/mnt/haraka/Haraka/node_modules/async/dist/async.js:424:21)
 [CRIT] [-] [core]     at /mnt/haraka/Haraka/node_modules/async/dist/async.js:321:20
 [CRIT] [-] [core]     at /mnt/haraka/Haraka/outbound/index.js:313:17
 [NOTICE] [-] [core] Shutting down
```
**System Info:**
2.8.27 + some local mods

**Comment by celesteking** [comment]
`discard()` there is very confusing. It almost feels like it would be invoked on error condition, but it goes on the contrary.
```js
            outbound.send_email(from, recip, data_lines.join(''), (code, msg2) => {
                if (code === constants.deny) {
                    // failed to even queue the mail
                    return self.double_bounce("Unable to queue the bounce message. Not sending bounce!");
                }
                self.discard();
            }, {origin: this});
```

**Comment by msimerson** [comment]
Stale, closing. Much of that code has since changed.
