### ISSUE TITLE
Critical error at startup with v2.8.27 due to haraka-config new version 1.0.19

### ISSUE THREAD

**Issue by DoobleD** [haraka/Haraka#2951]
**Describe the bug**
Haraka gets a critical error at startup due to an unresolved promise. 

Haraka's 2.8.27 package.json [requires haraka-config >= 1.0.15](https://github.com/haraka/Haraka/blob/8582195a405224437a90add401762b12e4937f4d/package.json#L34), thus installs [haraka-coonfig 1.0.19](https://github.com/haraka/haraka-config) rolled out 3 days ago and causing the issue (relates to configfile.read_dir being promisified).

Reverting haraka-config to 1.0.18 temporarily solves the issue.

**Expected behavior**
Haraka should run.

**Observed behavior**
Critical error at startup:

```
2021-06-13 18:53:13.905352480  2021-06-13T16:53:13.905Z [INFO] [-] [core] getting SocketOpts for SMTPS server
2021-06-13 18:53:13.906722478  2021-06-13T16:53:13.906Z [CRIT] [-] [core] TypeError: Cannot read property 'then' of undefined
2021-06-13 18:53:13.906794173  2021-06-13T16:53:13.906Z [CRIT] [-] [core]     at Config.getDir (/usr/lib/node_modules/Haraka/node_modules/haraka-config/config.js:55:68)
2021-06-13 18:53:13.906796957  2021-06-13T16:53:13.906Z [CRIT] [-] [core]     at Object.exports.get_certs_dir (/usr/lib/node_modules/Haraka/tls_socket.js:413:17)
2021-06-13 18:53:13.906819786  2021-06-13T16:53:13.906Z [CRIT] [-] [core]     at Object.exports.getSocketOpts (/usr/lib/node_modules/Haraka/tls_socket.js:500:10)
2021-06-13 18:53:13.906879468  2021-06-13T16:53:13.906Z [CRIT] [-] [core]     at Object.Server.get_smtp_server (/usr/lib/node_modules/Haraka/server.js:381:20)
2021-06-13 18:53:13.906895236  2021-06-13T16:53:13.906Z [CRIT] [-] [core]     at setupListener (/usr/lib/node_modules/Haraka/server.js:416:20)
2021-06-13 18:53:13.906912454  2021-06-13T16:53:13.906Z [CRIT] [-] [core]     at /usr/lib/node_modules/Haraka/node_modules/async/dist/async.js:2154:44
2021-06-13 18:53:13.906976926  2021-06-13T16:53:13.906Z [CRIT] [-] [core]     at eachOfArrayLike (/usr/lib/node_modules/Haraka/node_modules/async/dist/async.js:500:13)
2021-06-13 18:53:13.906979647  2021-06-13T16:53:13.906Z [CRIT] [-] [core]     at eachOf (/usr/lib/node_modules/Haraka/node_modules/async/dist/async.js:551:16)
2021-06-13 18:53:13.907002374  2021-06-13T16:53:13.906Z [CRIT] [-] [core]     at awaitable (/usr/lib/node_modules/Haraka/node_modules/async/dist/async.js:208:32)
2021-06-13 18:53:13.907067694  2021-06-13T16:53:13.907Z [CRIT] [-] [core]     at Object.eachLimit (/usr/lib/node_modules/Haraka/node_modules/async/dist/async.js:2216:16)
```

**Steps To Reproduce**

Clone Haraka branch 2.8.27, npm install, and start the server.

**System Info:**

```
Node | v14.17.0
OS | Linux <obfusacted.com> 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 GNU/Linux
openssl | OpenSSL 1.1.1k  25 Mar 2021
```

**Comment by msimerson** [comment]
Hmmm, I have cloned Haraka 2.8.27, verified that haraka-config 1.0.19 was installed by npm, and everything is working normally for me. I noticed my deployment had node 12 so I tried again with node 14 (same as yours) and everything is working normally for me. When I have a few more moments to poke at this I'll try again on Linux (vs FreeBSD).

**Comment by DoobleD** [comment]
Thanks for looking at it @msimerson! I'm not sure what's happening, I'll try again soon see if I can find a particular reason for this difference in behavior and I'll let you know.

**Comment by DoobleD** [comment]
Ok I had not realized it initially but this actually only happens with my config and/or plugins folder. It doesn't happen when generating a new folder with `haraka -i /path/to/haraka_test`. 

Sorry for the misleading report! I'll try to isolate what exactly in my config and/or plugin folder causes the promise error with haraka-config 1.0.19.

**Comment by DoobleD** [comment]
Oookay, this is my fault, I had my setup script override `configfile.js` with an older version of the file. Removing that and everything works great. Apologies for the waste of time @msimerson!
