### ISSUE TITLE
TLS plugin crashes when STARTTLS fails

### ISSUE THREAD

**Issue by lnedry** [haraka/Haraka#3180]
**Describe the bug**

TLS plugin crashes when STARTTLS fails.

**Expected behavior**

A key/value pair should have been created in Redis. My guess is that this plugin needs to be refactored to use promises with calls to Redis.

**Steps To Reproduce**

Receive an email from a server that doesn't use STARTTLS.

**System Info:**

Haraka | Haraka.js — Version: 3.0.1
 --- | :--- 
Node | v18.16.0
OS | Linux mx4 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux
openssl | OpenSSL 1.1.1n  15 Mar 2022

**Additional context**

Plugin tls failed: TypeError: server.notes.redis.setex is not a function
    at exports.set_notls (/usr/lib/node_modules/Haraka/plugins/tls.js:78:24)
    at Notes.nextOnce [as cleanUpDisconnect] (/usr/lib/node_modules/Haraka/plugins/tls.js:100:16)
    at exports.hook_disconnect (/usr/lib/node_modules/Haraka/plugins/tls.js:133:26)
    at plugins.run_next_hook (/usr/lib/node_modules/Haraka/plugins.js:535:28)
    at callback (/usr/lib/node_modules/Haraka/plugins.js:488:32)
    at exports.hook_disconnect (/usr/lib/node_modules/Haraka/plugins/process_title.js:179:5)
    at plugins.run_next_hook (/usr/lib/node_modules/Haraka/plugins.js:535:28)
    at plugins.run_hooks (/usr/lib/node_modules/Haraka/plugins.js:444:13)
    at /usr/lib/node_modules/Haraka/connection.js:608:21
    at Connection.reset_transaction (/usr/lib/node_modules/Haraka/connection.js:657:21)

**Comment by msimerson** [comment]
Fixed by #3174
