### ISSUE TITLE
Error installing on Mac OS X Maverick, Node.js v 0.12, NPM 2.7.5

### ISSUE THREAD

**Issue by wpoosanguansit** [haraka/Haraka#977]
I do get erorrs as below which I believe is from node-gyp rebuild.  Somehow I could install node-gyp find when I do npm install -g node-gyp alone.  But when I tried to install Haraka that is when I get the errors:

> node-syslog@1.1.7 install /usr/local/lib/node_modules/Haraka/node_modules/node-syslog
> node-gyp rebuild

  CXX(target) Release/obj.target/syslog/syslog.o
In file included from ../syslog.cc:1:
../node-syslog.h:22:45: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> init   (const v8::Arguments& args);
                                                   ^~~~~~~~~~~~~
                                                   v8::internal::Arguments
/Users/poosangw/.node-gyp/0.12.2/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../syslog.cc:1:
../node-syslog.h:23:42: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> log (const v8::Arguments& args);
                                                ^~~~~~~~~~~~~
                                                v8::internal::Arguments
/Users/poosangw/.node-gyp/0.12.2/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../syslog.cc:1:
../node-syslog.h:24:46: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> setMask (const v8::Arguments& args);
                                                    ^~~~~~~~~~~~~
                                                    v8::internal::Arguments
/Users/poosangw/.node-gyp/0.12.2/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../syslog.cc:1:
../node-syslog.h:25:46: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> destroy (const v8::Arguments& args);
                                                    ^~~~~~~~~~~~~
                                                    v8::internal::Arguments
/Users/poosangw/.node-gyp/0.12.2/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../syslog.cc:13:52: error: too few arguments to function call, at least argument 'isolate' must be specified
        Local<FunctionTemplate> t = FunctionTemplate::New();
                                    ~~~~~~~~~~~~~~~~~~~~~ ^
/Users/poosangw/.node-gyp/0.12.2/deps/v8/include/v8.h:3455:3: note: 'New' declared here
  static Local<FunctionTemplate> New(
  ^
../syslog.cc:14:55: error: 'New' is a private member of 'v8::PersistentBase<v8::FunctionTemplate>'
        constructor_template = Persistent<FunctionTemplate>::New(t);
                                                             ^
/Users/poosangw/.node-gyp/0.12.2/deps/v8/include/v8.h:572:23: note: declared private here
  V8_INLINE static T* New(Isolate* isolate, T* that);
                      ^
../syslog.cc:14:60: error: too few arguments to function call, expected 2, have 1
        constructor_template = Persistent<FunctionTemplate>::New(t);
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
/Users/poosangw/.node-gyp/0.12.2/deps/v8/include/v8.h:572:3: note: 'New' declared here
  V8_INLINE static T* New(Isolate* isolate, T* that);
  ^
/Users/poosangw/.node-gyp/0.12.2/deps/v8/include/v8config.h:289:20: note: expanded from macro 'V8_INLINE'
# define V8_INLINE inline __attribute__((always_inline))
                   ^
../syslog.cc:15:22: error: member reference type 'Persistent<v8::FunctionTemplate>' is not a pointer; maybe you meant to use '.'?
        constructor_template->InstanceTemplate()->SetInternalFieldCount(1);
        ~~~~~~~~~~~~~~~~~~~~^~
                            .
../syslog.cc:15:24: error: no member named 'InstanceTemplate' in 'v8::Persistent<v8::FunctionTemplate, v8::NonCopyablePersistentTraits<v8::FunctionTemplate> >'
        constructor_template->InstanceTemplate()->SetInternalFieldCount(1);
        ~~~~~~~~~~~~~~~~~~~~  ^
../syslog.cc:16:22: error: member reference type 'Persistent<v8::FunctionTemplate>' is not a pointer; maybe you meant to use '.'?
        constructor_template->SetClassName(String::NewSymbol("Syslog"));
        ~~~~~~~~~~~~~~~~~~~~^~
                            .
../syslog.cc:16:24: error: no member named 'SetClassName' in 'v8::Persistent<v8::FunctionTemplate, v8::NonCopyablePersistentTraits<v8::FunctionTemplate> >'
        constructor_template->SetClassName(String::NewSymbol("Syslog"));
        ~~~~~~~~~~~~~~~~~~~~  ^
../syslog.cc:16:45: error: no member named 'NewSymbol' in 'v8::String'
        constructor_template->SetClassName(String::NewSymbol("Syslog"));
                                           ~~~~~~~~^
../syslog.cc:19:2: error: no matching function for call to 'NODE_SET_METHOD'
        NODE_SET_METHOD(constructor_template, "init", Syslog::init);
        ^~~~~~~~~~~~~~~
/Users/poosangw/.node-gyp/0.12.2/src/node.h:240:25: note: expanded from macro 'NODE_SET_METHOD'
#define NODE_SET_METHOD node::NODE_SET_METHOD
                        ^~~~~~~~~~~~~~~~~~~~~
/Users/poosangw/.node-gyp/0.12.2/src/node.h:228:13: note: candidate function [with TypeName = v8::Persistent<v8::FunctionTemplate, v8::NonCopyablePersistentTraits<v8::FunctionTemplate> >] not viable: no
      known conversion from 'v8::Handle<v8::Value> (const v8::internal::Arguments &)' to 'v8::FunctionCallback' (aka 'void (*)(const FunctionCallbackInfo<v8::Value> &)') for 3rd argument
inline void NODE_SET_METHOD(const TypeName& recv,
            ^
../syslog.cc:20:2: error: no matching function for call to 'NODE_SET_METHOD'
        NODE_SET_METHOD(constructor_template, "log", Syslog::log);
        ^~~~~~~~~~~~~~~
/Users/poosangw/.node-gyp/0.12.2/src/node.h:240:25: note: expanded from macro 'NODE_SET_METHOD'
#define NODE_SET_METHOD node::NODE_SET_METHOD
                        ^~~~~~~~~~~~~~~~~~~~~
/Users/poosangw/.node-gyp/0.12.2/src/node.h:228:13: note: candidate function [with TypeName = v8::Persistent<v8::FunctionTemplate, v8::NonCopyablePersistentTraits<v8::FunctionTemplate> >] not viable: no
      known conversion from 'v8::Handle<v8::Value> (const v8::internal::Arguments &)' to 'v8::FunctionCallback' (aka 'void (*)(const FunctionCallbackInfo<v8::Value> &)') for 3rd argument
inline void NODE_SET_METHOD(const TypeName& recv,
            ^
../syslog.cc:21:2: error: no matching function for call to 'NODE_SET_METHOD'
        NODE_SET_METHOD(constructor_template, "setMask", Syslog::setMask);
        ^~~~~~~~~~~~~~~
/Users/poosangw/.node-gyp/0.12.2/src/node.h:240:25: note: expanded from macro 'NODE_SET_METHOD'
#define NODE_SET_METHOD node::NODE_SET_METHOD
                        ^~~~~~~~~~~~~~~~~~~~~
/Users/poosangw/.node-gyp/0.12.2/src/node.h:228:13: note: candidate function [with TypeName = v8::Persistent<v8::FunctionTemplate, v8::NonCopyablePersistentTraits<v8::FunctionTemplate> >] not viable: no
      known conversion from 'v8::Handle<v8::Value> (const v8::internal::Arguments &)' to 'v8::FunctionCallback' (aka 'void (*)(const FunctionCallbackInfo<v8::Value> &)') for 3rd argument
inline void NODE_SET_METHOD(const TypeName& recv,
            ^
../syslog.cc:22:2: error: no matching function for call to 'NODE_SET_METHOD'
        NODE_SET_METHOD(constructor_template, "close", Syslog::destroy);
        ^~~~~~~~~~~~~~~
/Users/poosangw/.node-gyp/0.12.2/src/node.h:240:25: note: expanded from macro 'NODE_SET_METHOD'
#define NODE_SET_METHOD node::NODE_SET_METHOD
                        ^~~~~~~~~~~~~~~~~~~~~
/Users/poosangw/.node-gyp/0.12.2/src/node.h:228:13: note: candidate function [with TypeName = v8::Persistent<v8::FunctionTemplate, v8::NonCopyablePersistentTraits<v8::FunctionTemplate> >] not viable: no
      known conversion from 'v8::Handle<v8::Value> (const v8::internal::Arguments &)' to 'v8::FunctionCallback' (aka 'void (*)(const FunctionCallbackInfo<v8::Value> &)') for 3rd argument
inline void NODE_SET_METHOD(const TypeName& recv,
            ^
../syslog.cc:24:22: error: no member named 'NewSymbol' in 'v8::String'
        target->Set(String::NewSymbol("Syslog"), constructor_template->GetFunction());
                    ~~~~~~~~^
../syslog.cc:28:22: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
Syslog::init ( const Arguments& args)
                     ^~~~~~~~~
                     v8::internal::Arguments
/Users/poosangw/.node-gyp/0.12.2/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../syslog.cc:30:14: error: calling a protected constructor of class 'v8::HandleScope'
        HandleScope scope;
                    ^
/Users/poosangw/.node-gyp/0.12.2/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/syslog/syslog.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/Haraka/node_modules/node-syslog
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
 
> strong-fork-syslog@1.2.3 install /usr/local/lib/node_modules/Haraka/node_modules/strong-fork-syslog
> node-gyp rebuild

  CXX(target) Release/obj.target/syslog/syslog.o
  SOLINK_MODULE(target) Release/syslog.node
  SOLINK_MODULE(target) Release/syslog.node: Finished
npm WARN optional dep failed, continuing node-syslog@1.1.7
 
> dtrace-provider@0.2.8 install /usr/local/lib/node_modules/Haraka/node_modules/ldapjs/node_modules/dtrace-provider
> node-gyp rebuild

  ACTION binding_gyp_libusdt_target_build_libusdt .
Building libusdt for x86_64
rm -f *.gch
rm -f *.o
rm -f libusdt.a
rm -f test_usdt
rm -f test_usdt32
rm -f test_usdt64
rm -f test_mem_usage
gcc -O2 -arch x86_64   -c -o usdt.o usdt.c
usdt.c:212:9: warning: implicit declaration of function 'usdt_dof_section_free' is invalid in C99 [-Wimplicit-function-declaration]
        usdt_dof_section_free(&strtab);
        ^
usdt.c:238:9: warning: implicit declaration of function 'usdt_dof_file_free' is invalid in C99 [-Wimplicit-function-declaration]
        usdt_dof_file_free(provider->file);
        ^

Any help is appreciated.

**Comment by Dexus** [comment]
Hi, you need g ++ 4.8 and later to build!

**Comment by trinitronx** [comment]
May be related: schamane/node-syslog#48

**Comment by msimerson** [comment]
We've resolved this issue (and others) by replacing node-syslog with modern-syslog.
